import type { ExpertRoleDefinition, ExpertTeamCategory, ExpertTeamDefinition } from './expertTeams';

const role = (
  key: string,
  name: string,
  description: string,
  skillIds: string[],
  category: ExpertTeamCategory,
  templateIds: string[] = [],
  keywords: string[] = [],
): ExpertRoleDefinition => ({
  key,
  name,
  description,
  systemPrompt: [
    `你是专家团中的${name}。`,
    `你的职责是：${description}`,
    '只处理与你职责直接相关的工作；信息不足时明确列出需要补充的材料。',
    '先给结论和关键依据，再给可执行步骤、风险与待确认项。',
    '完成后把结构化结果交还主理人，不越权代表整个专家团作最终决策。',
  ].join('\n'),
  skillIds,
  avatarHints: { templateIds, keywords, category },
});

const lead = (
  key: string,
  name: string,
  description: string,
  category: ExpertTeamCategory,
  templateIds: string[] = [],
  keywords: string[] = [],
): ExpertRoleDefinition => role(key, name, description, [], category, templateIds, keywords);

export const EXTRA_ENTERPRISE_EXPERT_TEAM_DEFINITIONS: ExpertTeamDefinition[] = [
  {
    id: 'strategic-planning',
    version: 1,
    name: '战略规划专家团',
    description: '从外部环境、竞争格局、业务组合到年度战略解码和执行追踪。',
    category: 'function',
    tags: ['企业战略', '年度规划', '战略解码'],
    legacyNames: [],
    lead: lead(
      'strategy_director',
      '战略规划总监',
      '明确战略议题、组织分析并把结论转化为可执行目标。',
      'function',
      ['project-manager'],
      ['战略', '规划', '总监'],
    ),
    roles: [
      role(
        'macro_environment_analyst',
        '宏观环境分析师',
        '分析政策、经济、社会、技术与行业周期对企业的影响。',
        ['web-search'],
        'function',
        [],
        ['宏观', '政策', '行业'],
      ),
      role(
        'competitive_strategy_advisor',
        '竞争战略顾问',
        '研究竞争格局、差异化路径、护城河和关键对手动作。',
        ['web-search', 'pptx'],
        'function',
        [],
        ['竞争', '战略', '顾问'],
      ),
      role(
        'business_portfolio_analyst',
        '业务组合分析师',
        '评估业务单元的增长、盈利、协同与资源优先级。',
        ['xlsx'],
        'finance',
        ['finance-analyst'],
        ['业务组合', '经营', '分析'],
      ),
      role(
        'strategy_execution_manager',
        '战略执行经理',
        '把战略拆解为年度目标、关键举措、责任人与里程碑。',
        ['create-plan', 'xlsx'],
        'function',
        ['project-manager'],
        ['战略执行', '项目', '目标'],
      ),
      role(
        'strategy_review_analyst',
        '战略复盘分析师',
        '设计战略指标、复盘机制和偏差纠正动作。',
        ['xlsx', 'pptx'],
        'function',
        ['data-analysis'],
        ['复盘', '指标', '战略'],
      ),
    ],
    prompts: {
      primary:
        '请组织一次企业年度战略规划，从外部环境、竞争格局、业务组合到目标和关键举措形成完整方案。',
      examples: [
        '请评估我们未来三年的增长方向，并给出业务取舍和资源配置建议。',
        '请把公司战略拆成年度目标、季度里程碑、负责人和复盘机制。',
        '请分析一个新市场是否值得进入，并列出关键假设和验证计划。',
      ],
    },
  },
  {
    id: 'market-intelligence',
    version: 1,
    name: '市场洞察专家团',
    description: '围绕市场规模、用户需求、竞争对手、趋势信号和机会优先级提供决策依据。',
    category: 'marketing',
    tags: ['市场调研', '竞品分析', '机会洞察'],
    legacyNames: [],
    lead: lead(
      'market_intelligence_director',
      '市场洞察总监',
      '定义研究问题、校验信息来源并整合市场判断。',
      'marketing',
      ['data-analysis'],
      ['市场', '洞察', '总监'],
    ),
    roles: [
      role(
        'market_sizing_analyst',
        '市场规模分析师',
        '估算总体市场、细分市场、增长率和关键假设。',
        ['web-search', 'xlsx'],
        'marketing',
        ['data-analysis'],
        ['市场规模', '分析', '行业'],
      ),
      role(
        'customer_insight_researcher',
        '客户洞察研究员',
        '研究客户画像、需求、购买动机、痛点和使用情境。',
        ['web-search', 'docx'],
        'marketing',
        [],
        ['用户研究', '客户', '洞察'],
      ),
      role(
        'competitor_analyst',
        '竞品分析师',
        '比较竞品定位、产品、价格、渠道、能力和近期动作。',
        ['web-search', 'xlsx'],
        'marketing',
        [],
        ['竞品', '市场', '分析'],
      ),
      role(
        'trend_researcher',
        '趋势研究员',
        '识别政策、技术、消费和行业趋势中的早期信号。',
        ['daily-trending', 'web-search'],
        'marketing',
        [],
        ['趋势', '热点', '研究'],
      ),
      role(
        'opportunity_analyst',
        '机会评估师',
        '对市场机会进行吸引力、可进入性和风险排序。',
        ['xlsx', 'pptx'],
        'function',
        ['data-analysis'],
        ['机会', '评估', '决策'],
      ),
    ],
    prompts: {
      primary: '请对我们所在市场做一次系统洞察，覆盖规模、客户、竞品、趋势和最值得优先验证的机会。',
      examples: [
        '请研究这个新赛道的市场规模、主要玩家和未来三年趋势。',
        '请对三家核心竞品做定位、产品、价格和渠道对比。',
        '请围绕目标客户设计一份需求研究框架并形成机会清单。',
      ],
    },
  },
  {
    id: 'brand-management',
    version: 1,
    name: '品牌管理专家团',
    description: '统一品牌定位、信息体系、视觉表达、传播内容和品牌资产评估。',
    category: 'marketing',
    tags: ['品牌定位', '视觉表达', '传播管理'],
    legacyNames: [],
    lead: lead(
      'brand_director',
      '品牌总监',
      '确定品牌目标、协调策略与创意并维护一致性。',
      'marketing',
      ['content-writer'],
      ['品牌', '创意', '总监'],
    ),
    roles: [
      role(
        'brand_strategist',
        '品牌策略师',
        '定义品牌定位、价值主张、差异化和品牌架构。',
        ['web-search', 'pptx'],
        'marketing',
        [],
        ['品牌策略', '定位', '顾问'],
      ),
      role(
        'messaging_architect',
        '品牌信息架构师',
        '建立核心信息、证据点、受众话术和品牌语气。',
        ['content-planner', 'docx'],
        'content',
        ['content-writer'],
        ['品牌', '文案', '信息'],
      ),
      role(
        'visual_identity_planner',
        '视觉识别策划师',
        '规划视觉语言、关键触点、素材规范和一致性检查。',
        ['canvas-design', 'seedream'],
        'design',
        [],
        ['视觉', '品牌', '设计'],
      ),
      role(
        'brand_content_editor',
        '品牌内容主编',
        '策划并审校品牌故事、活动、产品和公关内容。',
        ['article-writer', 'content-planner'],
        'content',
        ['content-writer'],
        ['内容', '品牌', '主编'],
      ),
      role(
        'brand_asset_analyst',
        '品牌资产分析师',
        '设计认知、偏好、声量和品牌贡献度指标。',
        ['xlsx', 'web-search'],
        'marketing',
        ['data-analysis'],
        ['品牌资产', '数据', '分析'],
      ),
    ],
    prompts: {
      primary: '请为我们的企业或产品建立一套品牌定位、核心信息、视觉方向和传播落地方案。',
      examples: [
        '请重新梳理我们的品牌定位、价值主张和目标客户表达。',
        '请为新品上市设计品牌信息体系、视觉主题和内容计划。',
        '请审计现有品牌触点，找出表达不一致和认知薄弱的问题。',
      ],
    },
  },
  {
    id: 'sales-growth',
    version: 1,
    name: '销售增长专家团',
    description: '覆盖目标市场、线索获取、商机推进、销售赋能、预测和业绩复盘。',
    category: 'marketing',
    tags: ['销售体系', '商机转化', '业绩增长'],
    legacyNames: [],
    lead: lead(
      'sales_growth_director',
      '销售增长总监',
      '制定销售目标、选择增长杠杆并推动跨角色协同。',
      'marketing',
      ['advisor-script'],
      ['销售', '增长', '总监'],
    ),
    roles: [
      role(
        'target_market_planner',
        '目标市场规划师',
        '定义细分市场、理想客户画像、区域与行业优先级。',
        ['web-search', 'xlsx'],
        'marketing',
        [],
        ['市场', '客户画像', '销售'],
      ),
      role(
        'lead_generation_advisor',
        '线索增长顾问',
        '设计获客渠道、线索标准、活动和触达路径。',
        ['content-planner', 'web-search'],
        'marketing',
        [],
        ['线索', '获客', '增长'],
      ),
      role(
        'sales_process_consultant',
        '销售流程顾问',
        '梳理阶段、资格判断、关键动作、退出条件和协作规则。',
        ['create-plan', 'docx'],
        'function',
        ['advisor-script'],
        ['销售流程', '顾问', '成交'],
      ),
      role(
        'sales_enablement_manager',
        '销售赋能经理',
        '准备话术、案例、异议处理、培训和销售工具。',
        ['docx', 'pptx'],
        'function',
        ['advisor-script'],
        ['销售赋能', '培训', '话术'],
      ),
      role(
        'sales_forecast_analyst',
        '销售预测分析师',
        '分析管道健康度、转化率、周期、预测偏差和目标差距。',
        ['xlsx'],
        'finance',
        ['data-analysis'],
        ['销售预测', '数据', '分析'],
      ),
    ],
    prompts: {
      primary: '请为我们设计一套从目标市场、线索获取到商机推进和销售预测的增长体系。',
      examples: [
        '请诊断我们销售转化率下降的原因，并提出分阶段改进动作。',
        '请为一个新行业客户群设计获客、销售话术和成交路径。',
        '请建立销售漏斗指标、周复盘机制和季度预测模型。',
      ],
    },
  },
  {
    id: 'key-account-management',
    version: 1,
    name: '大客户经营专家团',
    description: '围绕关键客户洞察、关系地图、解决方案、商务推进、交付协同和续约增长。',
    category: 'marketing',
    tags: ['大客户', '解决方案销售', '续约增长'],
    legacyNames: [],
    lead: lead(
      'key_account_director',
      '大客户经营总监',
      '统筹关键客户策略、关系、方案和商业结果。',
      'marketing',
      ['advisor-script'],
      ['大客户', '经营', '总监'],
    ),
    roles: [
      role(
        'account_researcher',
        '客户研究经理',
        '研究客户战略、组织、业务优先级和近期关键事件。',
        ['web-search', 'docx'],
        'marketing',
        [],
        ['客户研究', '行业', '经理'],
      ),
      role(
        'stakeholder_mapper',
        '关键关系规划师',
        '绘制决策链、影响者、支持者、阻力和关系行动。',
        ['wecomcli-contact', 'xlsx'],
        'platform',
        [],
        ['客户关系', '决策链', '规划'],
      ),
      role(
        'solution_sales_consultant',
        '解决方案销售顾问',
        '把客户问题转化为价值方案、演示路径和验证计划。',
        ['pptx', 'docx'],
        'marketing',
        ['advisor-script'],
        ['解决方案', '销售', '顾问'],
      ),
      role(
        'commercial_negotiation_advisor',
        '商务谈判顾问',
        '设计报价边界、交换条件、谈判策略和审批事项。',
        ['xlsx', 'docx'],
        'finance',
        [],
        ['商务', '谈判', '报价'],
      ),
      role(
        'renewal_growth_manager',
        '续约增长经理',
        '跟踪价值实现、风险信号、续约节奏和增购机会。',
        ['create-plan', 'wecomcli-todo'],
        'function',
        ['project-manager'],
        ['续约', '客户成功', '增长'],
      ),
    ],
    prompts: {
      primary: '请为一个关键企业客户制定账户经营计划，覆盖客户洞察、关系、方案、谈判、交付和续约。',
      examples: [
        '请为这家战略客户建立决策链地图和未来 90 天推进计划。',
        '请设计一次面向客户高层的解决方案汇报和商务谈判策略。',
        '请诊断大客户续约风险并安排价值证明和挽回动作。',
      ],
    },
  },
  {
    id: 'ecommerce-operations',
    version: 1,
    name: '电商运营专家团',
    description: '协同商品、内容、活动、投放、用户和数据运营，提升电商经营结果。',
    category: 'ecommerce',
    tags: ['商品运营', '活动增长', '电商分析'],
    legacyNames: [],
    lead: lead(
      'ecommerce_director',
      '电商运营总监',
      '制定经营目标、协调运营角色并控制活动节奏。',
      'ecommerce',
      ['after-sales-ticket'],
      ['电商', '运营', '总监'],
    ),
    roles: [
      role(
        'merchandise_operator',
        '商品运营经理',
        '规划商品结构、价格带、组合、上新和生命周期。',
        ['xlsx', 'web-search'],
        'ecommerce',
        [],
        ['商品', '电商', '运营'],
      ),
      role(
        'store_content_operator',
        '店铺内容运营',
        '优化商品信息、详情页、店铺内容和转化表达。',
        ['article-writer', 'canvas-design'],
        'content',
        ['product-copy-optimizer'],
        ['店铺', '内容', '商品'],
      ),
      role(
        'campaign_operator',
        '活动运营经理',
        '设计活动机制、资源位、节奏、库存和复盘方案。',
        ['create-plan', 'xlsx'],
        'ecommerce',
        [],
        ['活动', '促销', '运营'],
      ),
      role(
        'performance_marketer',
        '效果投放经理',
        '规划投放目标、素材测试、预算分配和归因分析。',
        ['content-planner', 'xlsx'],
        'marketing',
        [],
        ['投放', '广告', '增长'],
      ),
      role(
        'ecommerce_analyst',
        '电商数据分析师',
        '分析流量、点击、转化、客单、复购和商品效率。',
        ['xlsx'],
        'ecommerce',
        ['data-analysis'],
        ['电商数据', '分析', '转化'],
      ),
    ],
    prompts: {
      primary: '请对我们的电商业务制定商品、内容、活动、投放和数据复盘一体化运营方案。',
      examples: [
        '请为一次新品首发设计商品、页面、活动和投放联动计划。',
        '请分析店铺转化率下降的原因，并给出分模块优化动作。',
        '请制定下个月电商经营目标、活动日历和数据看板。',
      ],
    },
  },
  {
    id: 'private-domain-growth',
    version: 1,
    name: '私域增长专家团',
    description: '规划企微获客、客户分层、内容触达、社群运营、活动转化和复购分析。',
    category: 'platform',
    tags: ['企业微信', '私域运营', '复购转化'],
    legacyNames: [],
    lead: lead(
      'private_domain_director',
      '私域增长总监',
      '设计私域增长路径、触达节奏和团队协同规则。',
      'platform',
      ['customer-support'],
      ['私域', '企微', '总监'],
    ),
    roles: [
      role(
        'traffic_acquisition_operator',
        '私域获客运营',
        '设计渠道活码、添加路径、承接话术和线索归因。',
        ['wecomcli-contact', 'wecomcli-msg'],
        'platform',
        [],
        ['获客', '企微', '运营'],
      ),
      role(
        'customer_segmentation_analyst',
        '客户分层分析师',
        '建立客户标签、分层规则、价值阶段和触达策略。',
        ['xlsx', 'wecomcli-contact'],
        'platform',
        ['data-analysis'],
        ['客户分层', '标签', '分析'],
      ),
      role(
        'community_operator',
        '社群运营经理',
        '规划社群定位、内容、互动、规则和转化活动。',
        ['content-planner', 'wecomcli-msg'],
        'platform',
        [],
        ['社群', '运营', '企微'],
      ),
      role(
        'lifecycle_content_planner',
        '生命周期内容策划',
        '针对新客、活跃、沉默和复购阶段设计内容。',
        ['content-planner', 'article-writer'],
        'content',
        ['content-writer'],
        ['内容', '生命周期', '策划'],
      ),
      role(
        'private_domain_analyst',
        '私域数据分析师',
        '分析添加、触达、活跃、转化、复购和流失指标。',
        ['xlsx'],
        'marketing',
        ['data-analysis'],
        ['私域数据', '转化', '分析'],
      ),
    ],
    prompts: {
      primary: '请为我们设计一套企业微信私域增长体系，覆盖获客、分层、内容、社群、转化和复购。',
      examples: [
        '请制定新客户添加企微后的 30 天培育和转化流程。',
        '请设计客户分层标签、触达规则和不同阶段的话术。',
        '请诊断私域活跃和复购下降的原因并给出改进方案。',
      ],
    },
  },
  {
    id: 'procurement-management',
    version: 1,
    name: '采购管理专家团',
    description: '覆盖需求计划、寻源比价、供应商评估、合同谈判、成本和采购风险。',
    category: 'function',
    tags: ['战略采购', '供应商管理', '采购降本'],
    legacyNames: [],
    lead: lead(
      'procurement_director',
      '采购管理总监',
      '统筹采购策略、供应商决策和成本风险平衡。',
      'function',
      ['project-manager'],
      ['采购', '供应商', '总监'],
    ),
    roles: [
      role(
        'demand_planning_buyer',
        '采购需求规划师',
        '汇总需求、定义规格、批量与采购时间计划。',
        ['xlsx', 'create-plan'],
        'function',
        [],
        ['采购计划', '需求', '规划'],
      ),
      role(
        'sourcing_specialist',
        '供应商寻源专员',
        '开展市场寻源、供应商初筛、询价和比价。',
        ['web-search', 'xlsx'],
        'function',
        [],
        ['供应商', '寻源', '采购'],
      ),
      role(
        'supplier_evaluation_manager',
        '供应商评估经理',
        '建立准入、能力、质量、交付和财务风险评价。',
        ['xlsx', 'docx'],
        'function',
        ['risk-assessment'],
        ['供应商', '评估', '经理'],
      ),
      role(
        'procurement_negotiator',
        '采购谈判顾问',
        '设计价格、账期、交付、质量和违约条款谈判策略。',
        ['docx', 'pdf'],
        'legal',
        [],
        ['采购', '谈判', '合同'],
      ),
      role(
        'procurement_cost_analyst',
        '采购成本分析师',
        '拆解总拥有成本、价格差异、降本机会和收益验证。',
        ['xlsx'],
        'finance',
        ['finance-analyst'],
        ['采购成本', '降本', '分析'],
      ),
    ],
    prompts: {
      primary: '请为这项采购制定从需求、寻源、评估、谈判到供应商管理的完整方案。',
      examples: [
        '请为一个关键原材料采购项目设计询价、比价和谈判流程。',
        '请建立供应商准入、分级、绩效和退出机制。',
        '请分析采购成本结构并提出可验证的降本动作。',
      ],
    },
  },
  {
    id: 'supply-chain-operations',
    version: 1,
    name: '供应链运营专家团',
    description: '联动需求预测、库存、计划、物流、供应风险和运营指标。',
    category: 'logistics',
    tags: ['供应链计划', '库存优化', '履约保障'],
    legacyNames: [],
    lead: lead(
      'supply_chain_director',
      '供应链运营总监',
      '平衡需求、供应、库存、成本和服务水平。',
      'logistics',
      ['project-manager'],
      ['供应链', '运营', '总监'],
    ),
    roles: [
      role(
        'demand_forecast_analyst',
        '需求预测分析师',
        '建立需求预测、季节性、促销影响和误差复盘。',
        ['xlsx'],
        'logistics',
        ['data-analysis'],
        ['需求预测', '供应链', '分析'],
      ),
      role(
        'supply_planner',
        '供应计划经理',
        '制定供给、产能、采购和交付协同计划。',
        ['xlsx', 'create-plan'],
        'logistics',
        [],
        ['供应计划', '产能', '经理'],
      ),
      role(
        'inventory_optimizer',
        '库存优化师',
        '设置安全库存、补货策略、周转目标和呆滞处理。',
        ['xlsx'],
        'logistics',
        [],
        ['库存', '补货', '优化'],
      ),
      role(
        'logistics_manager',
        '物流运营经理',
        '优化运输、仓配、时效、成本和异常处理。',
        ['xlsx', 'web-search'],
        'logistics',
        [],
        ['物流', '运输', '仓储'],
      ),
      role(
        'supply_risk_analyst',
        '供应风险分析师',
        '识别供应中断、单一来源、价格和地缘风险。',
        ['web-search', 'xlsx'],
        'logistics',
        ['risk-assessment'],
        ['供应风险', '供应链', '预警'],
      ),
    ],
    prompts: {
      primary: '请诊断我们的供应链，并给出需求预测、库存、供应计划、物流和风险协同方案。',
      examples: [
        '请分析库存积压和缺货同时发生的原因并提出整改计划。',
        '请为旺季制定需求预测、备货、产能和物流保障方案。',
        '请建立供应链风险地图、预警指标和应急预案。',
      ],
    },
  },
  {
    id: 'production-operations',
    version: 1,
    name: '生产运营专家团',
    description: '围绕产能、排产、现场效率、设备、物料和持续改善提升生产绩效。',
    category: 'function',
    tags: ['生产计划', '精益改善', '设备效率'],
    legacyNames: [],
    lead: lead(
      'production_director',
      '生产运营总监',
      '统筹交付、质量、成本、安全和现场改善。',
      'function',
      ['project-manager'],
      ['生产', '工厂', '总监'],
    ),
    roles: [
      role(
        'capacity_planner',
        '产能规划师',
        '分析产能负荷、瓶颈、班次和扩产需求。',
        ['xlsx'],
        'function',
        [],
        ['产能', '生产', '规划'],
      ),
      role(
        'production_scheduler',
        '生产计划员',
        '制定主生产计划、排产规则、物料齐套和交付节奏。',
        ['xlsx', 'create-plan'],
        'function',
        [],
        ['排产', '生产计划', '运营'],
      ),
      role(
        'lean_improvement_engineer',
        '精益改善工程师',
        '识别浪费、节拍、布局和标准作业改善机会。',
        ['create-plan', 'xlsx'],
        'function',
        [],
        ['精益', '改善', '工程师'],
      ),
      role(
        'equipment_manager',
        '设备管理工程师',
        '规划设备点检、保养、故障分析和备件管理。',
        ['xlsx', 'docx'],
        'tech',
        [],
        ['设备', '运维', '工程师'],
      ),
      role(
        'production_performance_analyst',
        '生产绩效分析师',
        '分析 OEE、良率、交付、工时和单位成本。',
        ['xlsx'],
        'function',
        ['data-analysis'],
        ['生产数据', '绩效', '分析'],
      ),
    ],
    prompts: {
      primary: '请对我们的生产运营做一次诊断，覆盖产能、排产、现场效率、设备和绩效改善。',
      examples: [
        '请分析当前产能瓶颈并制定两个月的改善计划。',
        '请建立生产排程、物料齐套和异常升级机制。',
        '请设计 OEE、良率、交付和成本的生产经营看板。',
      ],
    },
  },
  {
    id: 'quality-management',
    version: 1,
    name: '质量管理专家团',
    description: '覆盖质量体系、来料、过程、客户质量、根因分析和持续改进。',
    category: 'function',
    tags: ['质量体系', '根因分析', '持续改进'],
    legacyNames: [],
    lead: lead(
      'quality_director',
      '质量管理总监',
      '统一质量标准、问题优先级和跨部门改善闭环。',
      'function',
      ['risk-assessment'],
      ['质量', '体系', '总监'],
    ),
    roles: [
      role(
        'quality_system_manager',
        '质量体系经理',
        '建立质量制度、流程、审核、记录和管理评审机制。',
        ['docx', 'pdf'],
        'function',
        [],
        ['质量体系', '审核', '经理'],
      ),
      role(
        'supplier_quality_engineer',
        '供应商质量工程师',
        '管理来料标准、供应商问题、审核和改善验证。',
        ['xlsx', 'docx'],
        'function',
        [],
        ['供应商质量', '工程师', '来料'],
      ),
      role(
        'process_quality_engineer',
        '过程质量工程师',
        '控制关键过程、检验点、能力指标和异常隔离。',
        ['xlsx', 'create-plan'],
        'function',
        [],
        ['过程质量', '生产', '工程师'],
      ),
      role(
        'customer_quality_manager',
        '客户质量经理',
        '处理客户投诉、8D、纠正预防和客户沟通。',
        ['docx', 'xlsx'],
        'function',
        ['customer-support'],
        ['客户质量', '投诉', '经理'],
      ),
      role(
        'root_cause_analyst',
        '质量根因分析师',
        '运用结构化方法识别根因、措施、责任和有效性。',
        ['create-plan', 'xlsx'],
        'function',
        ['risk-assessment'],
        ['根因', '质量', '分析'],
      ),
    ],
    prompts: {
      primary: '请建立一套从质量体系、供应商、过程到客户投诉和持续改进的质量管理方案。',
      examples: [
        '请对一次重大客户质量投诉组织根因分析和 8D 改善。',
        '请建立供应商质量准入、绩效、审核和整改机制。',
        '请设计生产过程质量控制点、指标和异常升级流程。',
      ],
    },
  },
  {
    id: 'project-management-office',
    version: 1,
    name: '项目管理办公室专家团',
    description: '建立项目组合、治理机制、计划、风险、资源、汇报和复盘标准。',
    category: 'function',
    tags: ['项目治理', '项目组合', '交付管理'],
    legacyNames: [],
    lead: lead(
      'pmo_director',
      'PMO 总监',
      '建立项目治理规则并协调组合优先级和资源冲突。',
      'function',
      ['project-manager'],
      ['PMO', '项目', '总监'],
    ),
    roles: [
      role(
        'portfolio_manager',
        '项目组合经理',
        '评估项目价值、优先级、依赖、容量和立项退出。',
        ['xlsx', 'pptx'],
        'function',
        ['project-manager'],
        ['项目组合', '经理', '战略'],
      ),
      role(
        'project_planner',
        '项目计划经理',
        '制定范围、WBS、进度、里程碑、责任和基线。',
        ['create-plan', 'xlsx'],
        'function',
        ['project-manager'],
        ['项目计划', '进度', '经理'],
      ),
      role(
        'project_risk_manager',
        '项目风险经理',
        '维护风险、问题、决策和变更控制机制。',
        ['xlsx', 'docx'],
        'function',
        ['risk-assessment'],
        ['项目风险', '问题', '经理'],
      ),
      role(
        'resource_coordinator',
        '项目资源协调经理',
        '分析资源需求、冲突、关键岗位和跨团队调度。',
        ['xlsx', 'wecomcli-todo'],
        'function',
        [],
        ['项目资源', '协调', '经理'],
      ),
      role(
        'project_reporting_analyst',
        '项目报告分析师',
        '统一状态口径、管理驾驶舱、周报和复盘。',
        ['pptx', 'xlsx'],
        'function',
        ['data-analysis'],
        ['项目报告', '数据', '分析'],
      ),
    ],
    prompts: {
      primary: '请为我们的多项目环境建立 PMO 治理体系，覆盖组合、计划、风险、资源和管理汇报。',
      examples: [
        '请评估当前项目组合并给出优先级和暂停建议。',
        '请为一个跨部门项目建立计划、风险、变更和周报机制。',
        '请设计项目管理驾驶舱和月度项目复盘会议。',
      ],
    },
  },
  {
    id: 'human-resources',
    version: 1,
    name: '人力资源专家团',
    description: '覆盖人力规划、岗位体系、绩效、薪酬、员工关系和人力数据。',
    category: 'hr',
    tags: ['人力规划', '绩效薪酬', '员工关系'],
    legacyNames: [],
    lead: lead(
      'hr_director',
      '人力资源总监',
      '统筹组织需求、人才机制、用工风险和人力效能。',
      'hr',
      ['hr-recruiter'],
      ['人力资源', 'HR', '总监'],
    ),
    roles: [
      role(
        'workforce_planner',
        '人力规划经理',
        '分析组织目标、编制、能力缺口和人力成本。',
        ['xlsx', 'create-plan'],
        'hr',
        ['hr-recruiter'],
        ['人力规划', '编制', '经理'],
      ),
      role(
        'job_architecture_consultant',
        '岗位体系顾问',
        '设计岗位族、职级、职责、任职资格和晋升通道。',
        ['docx', 'xlsx'],
        'hr',
        [],
        ['岗位', '职级', '顾问'],
      ),
      role(
        'performance_manager',
        '绩效管理经理',
        '建立目标、评价、校准、反馈和绩效改进机制。',
        ['docx', 'xlsx'],
        'hr',
        [],
        ['绩效', '目标', '经理'],
      ),
      role(
        'compensation_analyst',
        '薪酬分析师',
        '分析薪酬结构、内部公平、市场竞争力和激励成本。',
        ['xlsx', 'web-search'],
        'hr',
        ['finance-analyst'],
        ['薪酬', '激励', '分析'],
      ),
      role(
        'employee_relations_advisor',
        '员工关系顾问',
        '处理制度沟通、申诉、劳动风险和员工体验问题。',
        ['docx', 'web-search'],
        'hr',
        ['hr-recruiter'],
        ['员工关系', '劳动', '顾问'],
      ),
    ],
    prompts: {
      primary: '请为我们的组织建立人力规划、岗位、绩效、薪酬和员工关系一体化管理方案。',
      examples: [
        '请根据明年业务目标制定人员编制、能力缺口和人力成本计划。',
        '请重构岗位职级、任职资格、绩效和晋升机制。',
        '请诊断员工流失和敬业度问题，并提出管理动作。',
      ],
    },
  },
  {
    id: 'talent-acquisition',
    version: 1,
    name: '招聘与人才专家团',
    description: '从人才画像、渠道、寻访、面试、评估到录用和入职提升招聘质量。',
    category: 'hr',
    tags: ['人才招聘', '面试评估', '雇主品牌'],
    legacyNames: [],
    lead: lead(
      'talent_acquisition_director',
      '招聘总监',
      '明确人才需求、组织招聘漏斗并控制人才质量。',
      'hr',
      ['hr-recruiter'],
      ['招聘', '人才', '总监'],
    ),
    roles: [
      role(
        'talent_profile_designer',
        '人才画像设计师',
        '把业务需求转化为岗位职责、能力和评估标准。',
        ['docx', 'web-search'],
        'hr',
        ['hr-recruiter'],
        ['人才画像', '岗位', '招聘'],
      ),
      role(
        'sourcing_recruiter',
        '人才寻访顾问',
        '设计渠道组合、搜索策略、触达信息和人才池。',
        ['web-search', 'wecomcli-contact'],
        'hr',
        ['hr-recruiter'],
        ['人才寻访', '招聘', '顾问'],
      ),
      role(
        'interview_architect',
        '面试体系设计师',
        '设计结构化面试、题库、评分表和面试官分工。',
        ['docx', 'xlsx'],
        'hr',
        [],
        ['面试', '评估', '设计'],
      ),
      role(
        'candidate_assessor',
        '候选人评估顾问',
        '综合履历、面试证据、能力风险和岗位匹配度。',
        ['docx', 'xlsx'],
        'hr',
        ['hr-recruiter'],
        ['候选人', '人才', '评估'],
      ),
      role(
        'onboarding_manager',
        '入职融入经理',
        '规划录用沟通、入职准备、试用期目标和融入检查。',
        ['create-plan', 'wecomcli-todo'],
        'hr',
        ['project-manager'],
        ['入职', '员工', '经理'],
      ),
    ],
    prompts: {
      primary: '请为这个关键岗位设计从人才画像、寻访、面试评估到录用入职的完整招聘方案。',
      examples: [
        '请为高级销售负责人建立人才画像、渠道和面试评分表。',
        '请诊断我们的招聘周期长和录用率低问题。',
        '请设计一套结构化面试、候选人校准和试用期验证机制。',
      ],
    },
  },
  {
    id: 'organization-development',
    version: 1,
    name: '组织发展专家团',
    description: '围绕组织诊断、架构、人才盘点、领导力、文化和变革提升组织能力。',
    category: 'hr',
    tags: ['组织诊断', '人才发展', '变革管理'],
    legacyNames: [],
    lead: lead(
      'organization_development_director',
      '组织发展总监',
      '识别组织能力问题并统筹架构、人才和变革方案。',
      'hr',
      ['project-manager'],
      ['组织发展', '人才', '总监'],
    ),
    roles: [
      role(
        'organization_diagnosis_consultant',
        '组织诊断顾问',
        '分析战略、结构、流程、权责、协作和能力问题。',
        ['docx', 'xlsx'],
        'hr',
        [],
        ['组织诊断', '顾问', '管理'],
      ),
      role(
        'organization_designer',
        '组织架构设计师',
        '设计组织单元、汇报关系、权责边界和协作机制。',
        ['pptx', 'docx'],
        'hr',
        [],
        ['组织架构', '设计', '管理'],
      ),
      role(
        'talent_review_manager',
        '人才盘点经理',
        '建立人才标准、九宫格、继任、关键岗位和发展动作。',
        ['xlsx', 'docx'],
        'hr',
        ['hr-recruiter'],
        ['人才盘点', '继任', '经理'],
      ),
      role(
        'leadership_development_advisor',
        '领导力发展顾问',
        '设计领导力模型、评估、培养和实践任务。',
        ['create-plan', 'pptx'],
        'education',
        [],
        ['领导力', '培训', '顾问'],
      ),
      role(
        'change_management_manager',
        '变革管理经理',
        '规划利益相关者、沟通、培训、阻力和落地追踪。',
        ['create-plan', 'docx'],
        'hr',
        ['project-manager'],
        ['变革', '组织', '经理'],
      ),
    ],
    prompts: {
      primary: '请对我们的组织能力做一次诊断，并给出架构、人才、领导力和变革落地方案。',
      examples: [
        '请评估当前组织架构是否支持未来三年的业务战略。',
        '请设计一次关键人才盘点、继任和发展计划。',
        '请为组织调整制定沟通、培训、阻力管理和落地追踪方案。',
      ],
    },
  },
  {
    id: 'administrative-office',
    version: 1,
    name: '行政办公专家团',
    description: '协同会议、日程、文档、任务、制度和行政服务，提升企业办公效率。',
    category: 'function',
    tags: ['行政办公', '会议协同', '制度流程'],
    legacyNames: [],
    lead: lead(
      'administration_director',
      '行政办公总监',
      '统一办公标准、协调事务并保障重要活动落地。',
      'function',
      ['project-manager'],
      ['行政', '办公', '总监'],
    ),
    roles: [
      role(
        'executive_assistant',
        '高管事务助理',
        '统筹重要日程、会议准备、材料和待办跟进。',
        ['wecomcli-schedule', 'wecomcli-todo'],
        'platform',
        [],
        ['高管助理', '日程', '办公'],
      ),
      role(
        'meeting_manager',
        '会议管理专员',
        '规划会议、参会人、议程、纪要和决议追踪。',
        ['wecomcli-meeting', 'wecomcli-doc'],
        'platform',
        [],
        ['会议', '纪要', '专员'],
      ),
      role(
        'document_administrator',
        '公文管理专员',
        '起草通知、制度、公文并维护版本和归档规范。',
        ['docx', 'wecomcli-doc'],
        'function',
        [],
        ['公文', '文档', '行政'],
      ),
      role(
        'office_service_manager',
        '办公服务经理',
        '管理场地、物资、供应商、活动和服务标准。',
        ['xlsx', 'create-plan'],
        'function',
        [],
        ['行政服务', '办公', '经理'],
      ),
      role(
        'administrative_process_analyst',
        '行政流程分析师',
        '梳理审批、服务流程、时效、成本和改进机会。',
        ['xlsx', 'create-plan'],
        'function',
        ['data-analysis'],
        ['行政流程', '效率', '分析'],
      ),
    ],
    prompts: {
      primary: '请为我们的企业办公建立会议、日程、文档、任务和行政服务协同机制。',
      examples: [
        '请组织一次经营管理会，准备议程、材料、纪要和决议跟踪。',
        '请梳理行政审批和办公服务流程并提出效率改进方案。',
        '请为一次重要客户来访制定完整接待和内部协同计划。',
      ],
    },
  },
  {
    id: 'data-analytics',
    version: 1,
    name: '企业数据分析专家团',
    description: '从指标口径、数据质量、分析建模、可视化到业务建议形成分析闭环。',
    category: 'function',
    tags: ['数据治理', '经营分析', '决策支持'],
    legacyNames: [],
    lead: lead(
      'analytics_director',
      '数据分析总监',
      '定义分析问题、控制数据质量并整合业务结论。',
      'function',
      ['data-analysis'],
      ['数据', '分析', '总监'],
    ),
    roles: [
      role(
        'metric_architect',
        '指标体系架构师',
        '定义业务目标、指标树、口径、维度和责任人。',
        ['xlsx', 'docx'],
        'function',
        ['data-analysis'],
        ['指标', '数据', '架构'],
      ),
      role(
        'data_quality_analyst',
        '数据质量分析师',
        '检查完整性、一致性、及时性、异常和数据血缘。',
        ['xlsx', 'local-tools'],
        'tech',
        ['data-analysis'],
        ['数据质量', '分析', '治理'],
      ),
      role(
        'business_analyst',
        '业务分析师',
        '围绕增长、转化、效率、结构和异常进行诊断。',
        ['xlsx', 'web-search'],
        'function',
        ['data-analysis'],
        ['业务数据', '经营', '分析'],
      ),
      role(
        'forecasting_analyst',
        '预测分析师',
        '建立趋势、情景、预测假设和误差评估。',
        ['xlsx', 'local-tools'],
        'finance',
        ['data-analysis'],
        ['预测', '数据', '分析'],
      ),
      role(
        'data_storytelling_designer',
        '数据表达设计师',
        '把分析结果转化为图表、报告、管理结论和行动。',
        ['pptx', 'xlsx'],
        'design',
        [],
        ['数据可视化', '报告', '设计'],
      ),
    ],
    prompts: {
      primary: '请基于我的业务数据建立指标口径、质量检查、分析框架和管理决策建议。',
      examples: [
        '请分析本月核心指标变化，定位驱动因素和异常。',
        '请为管理层建立一套指标树、看板和复盘机制。',
        '请检查这份数据的质量并说明哪些结论可以可信使用。',
      ],
    },
  },
  {
    id: 'ai-transformation',
    version: 1,
    name: 'AI 转型专家团',
    description: '从场景盘点、价值评估、技术架构、数据治理到试点和规模化推动企业 AI 转型。',
    category: 'tech',
    tags: ['AI 战略', '场景落地', '转型治理'],
    legacyNames: [],
    lead: lead(
      'ai_transformation_director',
      'AI 转型总监',
      '统筹 AI 场景、价值、技术、治理和组织落地。',
      'tech',
      ['project-manager'],
      ['AI', '转型', '总监'],
    ),
    roles: [
      role(
        'ai_use_case_consultant',
        'AI 场景顾问',
        '盘点流程痛点、识别 AI 场景并定义用户与价值。',
        ['web-search', 'create-plan'],
        'tech',
        [],
        ['AI 场景', '顾问', '业务'],
      ),
      role(
        'ai_value_analyst',
        'AI 价值分析师',
        '评估收益、成本、风险、可行性和场景优先级。',
        ['xlsx'],
        'finance',
        ['data-analysis'],
        ['AI 价值', 'ROI', '分析'],
      ),
      role(
        'ai_solution_architect',
        'AI 解决方案架构师',
        '设计模型、知识、工具、流程、人机协同和系统集成。',
        ['web-search', 'local-tools'],
        'tech',
        [],
        ['AI 架构', '技术', '解决方案'],
      ),
      role(
        'ai_data_governance_manager',
        'AI 数据治理经理',
        '规划数据来源、质量、权限、隐私和知识更新机制。',
        ['docx', 'xlsx'],
        'tech',
        ['risk-assessment'],
        ['数据治理', 'AI', '经理'],
      ),
      role(
        'ai_adoption_manager',
        'AI 推广与变革经理',
        '设计试点、培训、使用规范、反馈和规模化推广。',
        ['create-plan', 'pptx'],
        'education',
        ['project-manager'],
        ['AI 推广', '培训', '变革'],
      ),
    ],
    prompts: {
      primary:
        '请为我们的企业制定 AI 转型路线图，覆盖场景、价值、技术、数据治理、试点和规模化推广。',
      examples: [
        '请盘点各部门适合落地 AI 的场景并按价值和难度排序。',
        '请为一个 AI 数字员工试点设计架构、数据、流程和验收指标。',
        '请制定企业 AI 使用规范、培训和规模化推广方案。',
      ],
    },
  },
  {
    id: 'information-security',
    version: 1,
    name: '信息安全专家团',
    description: '覆盖安全治理、架构、身份权限、应用数据安全、事件响应和合规整改。',
    category: 'tech',
    tags: ['安全治理', '风险评估', '事件响应'],
    legacyNames: [],
    lead: lead(
      'security_director',
      '信息安全总监',
      '统筹安全风险、控制体系、事件响应和整改优先级。',
      'tech',
      ['risk-assessment'],
      ['信息安全', '风险', '总监'],
    ),
    roles: [
      role(
        'security_governance_manager',
        '安全治理经理',
        '建立安全制度、责任、资产、风险和审计机制。',
        ['docx', 'xlsx'],
        'tech',
        ['risk-assessment'],
        ['安全治理', '制度', '经理'],
      ),
      role(
        'security_architect',
        '安全架构师',
        '评估网络、云、终端、系统边界和纵深防御。',
        ['web-search', 'local-tools'],
        'tech',
        [],
        ['安全架构', '技术', '工程师'],
      ),
      role(
        'identity_access_specialist',
        '身份权限专家',
        '设计身份、认证、授权、最小权限和账号生命周期。',
        ['docx', 'local-tools'],
        'tech',
        [],
        ['身份', '权限', '安全'],
      ),
      role(
        'application_data_security_engineer',
        '应用与数据安全工程师',
        '评估开发、接口、漏洞、加密、数据分类和防泄漏。',
        ['web-search', 'local-tools'],
        'tech',
        [],
        ['应用安全', '数据安全', '工程师'],
      ),
      role(
        'incident_response_manager',
        '安全事件响应经理',
        '建立监测、分级、处置、取证、通报和复盘机制。',
        ['create-plan', 'docx'],
        'tech',
        ['risk-assessment'],
        ['事件响应', '安全', '经理'],
      ),
    ],
    prompts: {
      primary: '请对我们的信息系统做一次安全体检，覆盖治理、架构、身份、应用数据和事件响应。',
      examples: [
        '请为一次系统上线制定安全评审、测试和整改清单。',
        '请设计企业身份权限、账号生命周期和最小权限机制。',
        '请为数据泄露事件建立应急响应、通报和复盘流程。',
      ],
    },
  },
  {
    id: 'internal-audit',
    version: 1,
    name: '内控审计专家团',
    description: '围绕流程、财务、合规、信息系统、舞弊风险和整改追踪开展企业内审。',
    category: 'finance',
    tags: ['内部控制', '风险审计', '整改闭环'],
    legacyNames: [],
    lead: lead(
      'internal_audit_director',
      '内审总监',
      '制定审计范围、分配测试并形成风险分级意见。',
      'finance',
      ['risk-assessment'],
      ['内审', '风控', '总监'],
    ),
    roles: [
      role(
        'process_auditor',
        '流程审计师',
        '审查流程设计、职责分离、审批、证据和执行偏差。',
        ['docx', 'xlsx'],
        'function',
        [],
        ['流程审计', '内控', '审计'],
      ),
      role(
        'financial_auditor',
        '财务审计师',
        '检查收入、成本、费用、资产、资金和会计控制。',
        ['xlsx', 'pdf'],
        'finance',
        ['finance-analyst'],
        ['财务审计', '报表', '审计'],
      ),
      role(
        'compliance_auditor',
        '合规审计师',
        '评估制度、监管要求、授权和合规执行证据。',
        ['web-search', 'docx'],
        'legal',
        ['legal-compliance'],
        ['合规', '审计', '制度'],
      ),
      role(
        'it_auditor',
        '信息系统审计师',
        '检查访问、变更、运维、备份、日志和系统控制。',
        ['local-tools', 'xlsx'],
        'tech',
        [],
        ['IT 审计', '系统', '安全'],
      ),
      role(
        'fraud_risk_analyst',
        '舞弊风险分析师',
        '识别利益冲突、异常交易、绕控和舞弊红旗。',
        ['xlsx', 'web-search'],
        'finance',
        ['risk-assessment'],
        ['舞弊', '风险', '分析'],
      ),
    ],
    prompts: {
      primary: '请对我们的关键业务流程开展一次内控审计，识别控制缺陷、风险等级和整改责任。',
      examples: [
        '请审计采购到付款流程的职责分离、审批和舞弊风险。',
        '请对销售收入、回款和折扣政策开展专项审计。',
        '请建立年度内审计划、审计底稿和整改追踪机制。',
      ],
    },
  },
  {
    id: 'commercial-due-diligence',
    version: 1,
    name: '商业尽调专家团',
    description: '从市场、客户、竞争、产品、运营、财务和风险评估投资或合作标的。',
    category: 'finance',
    tags: ['商业尽调', '投资决策', '风险验证'],
    legacyNames: [],
    lead: lead(
      'due_diligence_director',
      '商业尽调总监',
      '定义尽调假设、组织证据验证并形成决策结论。',
      'finance',
      ['risk-assessment'],
      ['尽调', '投资', '总监'],
    ),
    roles: [
      role(
        'market_due_diligence_analyst',
        '市场尽调分析师',
        '验证市场规模、增长、驱动因素和细分机会。',
        ['web-search', 'xlsx'],
        'marketing',
        ['data-analysis'],
        ['市场尽调', '行业', '分析'],
      ),
      role(
        'customer_due_diligence_researcher',
        '客户尽调研究员',
        '验证客户结构、需求、留存、集中度和访谈证据。',
        ['docx', 'xlsx'],
        'marketing',
        [],
        ['客户尽调', '研究', '访谈'],
      ),
      role(
        'competitive_due_diligence_analyst',
        '竞争尽调分析师',
        '评估竞争格局、差异化、替代风险和护城河。',
        ['web-search', 'pptx'],
        'function',
        [],
        ['竞争尽调', '竞品', '分析'],
      ),
      role(
        'operational_due_diligence_manager',
        '运营尽调经理',
        '检查产品、交付、供应链、团队和规模化能力。',
        ['docx', 'xlsx'],
        'function',
        [],
        ['运营尽调', '交付', '经理'],
      ),
      role(
        'financial_due_diligence_analyst',
        '财务尽调分析师',
        '分析收入质量、盈利、现金流、预测和关键风险。',
        ['xlsx', 'pdf'],
        'finance',
        ['finance-analyst'],
        ['财务尽调', '现金流', '分析'],
      ),
    ],
    prompts: {
      primary: '请对这个投资或合作标的开展商业尽调，覆盖市场、客户、竞争、运营、财务和关键风险。',
      examples: [
        '请为收购一家 SaaS 公司设计商业尽调框架和资料清单。',
        '请验证这个项目的市场规模、客户质量和增长假设。',
        '请把尽调发现整理成红旗、待验证事项和投资决策建议。',
      ],
    },
  },
  {
    id: 'investment-financing',
    version: 1,
    name: '投融资专家团',
    description: '覆盖融资策略、商业计划、财务模型、估值、投资人材料、交易结构和尽调准备。',
    category: 'finance',
    tags: ['融资规划', '估值模型', '交易支持'],
    legacyNames: [],
    lead: lead(
      'corporate_finance_director',
      '投融资总监',
      '统筹资本目标、融资路径、估值和交易执行。',
      'finance',
      ['finance-analyst'],
      ['投融资', '资本', '总监'],
    ),
    roles: [
      role(
        'financing_strategy_advisor',
        '融资策略顾问',
        '评估融资目的、金额、节奏、工具和投资人类型。',
        ['web-search', 'create-plan'],
        'finance',
        [],
        ['融资', '资本', '顾问'],
      ),
      role(
        'business_plan_writer',
        '商业计划书顾问',
        '搭建市场、产品、商业模式、团队和增长叙事。',
        ['pptx', 'docx'],
        'finance',
        ['content-writer'],
        ['商业计划书', '融资', '顾问'],
      ),
      role(
        'financial_modeling_analyst',
        '财务模型分析师',
        '建立收入、成本、现金流、情景和融资需求模型。',
        ['xlsx'],
        'finance',
        ['finance-analyst'],
        ['财务模型', '融资', '分析'],
      ),
      role(
        'valuation_advisor',
        '企业估值顾问',
        '运用可比、现金流和交易方法形成估值区间。',
        ['xlsx', 'web-search'],
        'finance',
        ['finance-analyst'],
        ['企业估值', '投资', '顾问'],
      ),
      role(
        'transaction_execution_manager',
        '交易执行经理',
        '规划材料、尽调、条款、审批和交割事项。',
        ['create-plan', 'docx'],
        'finance',
        ['project-manager'],
        ['交易', '尽调', '经理'],
      ),
    ],
    prompts: {
      primary: '请为我们的融资需求制定策略，并准备商业计划、财务模型、估值和交易执行方案。',
      examples: [
        '请为 A 轮融资设计金额、节奏、投资人画像和材料清单。',
        '请建立三年财务模型、融资需求和估值敏感性分析。',
        '请审查商业计划书并提出投资人最可能追问的问题。',
      ],
    },
  },
  {
    id: 'global-expansion',
    version: 1,
    name: '企业出海专家团',
    description: '围绕市场选择、本地化、渠道、跨境合规、供应链和落地计划支持国际化。',
    category: 'crossBorder',
    tags: ['海外市场', '本地化', '跨境经营'],
    legacyNames: [],
    lead: lead(
      'global_expansion_director',
      '出海业务总监',
      '统筹国家选择、进入模式、风险和跨职能落地。',
      'crossBorder',
      ['project-manager'],
      ['出海', '海外', '总监'],
    ),
    roles: [
      role(
        'country_market_analyst',
        '海外市场分析师',
        '评估国家市场规模、竞争、客户、政策和进入吸引力。',
        ['web-search', 'xlsx'],
        'crossBorder',
        [],
        ['海外市场', '国家', '分析'],
      ),
      role(
        'localization_strategist',
        '本地化策略师',
        '规划产品、价格、语言、文化、服务和运营本地化。',
        ['web-search', 'docx'],
        'crossBorder',
        [],
        ['本地化', '产品', '策略'],
      ),
      role(
        'global_channel_manager',
        '海外渠道经理',
        '设计直销、代理、平台、合作伙伴和渠道管理机制。',
        ['web-search', 'create-plan'],
        'crossBorder',
        [],
        ['海外渠道', '销售', '经理'],
      ),
      role(
        'cross_border_compliance_advisor',
        '跨境合规顾问',
        '识别主体、税务、数据、贸易、用工和营销合规。',
        ['web-search', 'pdf'],
        'legal',
        ['legal-compliance'],
        ['跨境合规', '法务', '顾问'],
      ),
      role(
        'global_operations_planner',
        '海外运营规划师',
        '制定供应、交付、客服、团队、预算和启动计划。',
        ['create-plan', 'xlsx'],
        'crossBorder',
        ['project-manager'],
        ['海外运营', '交付', '规划'],
      ),
    ],
    prompts: {
      primary: '请为我们的产品制定企业出海方案，覆盖市场选择、本地化、渠道、合规和运营落地。',
      examples: [
        '请比较三个目标国家并推荐首个进入市场。',
        '请为进入东南亚市场设计产品本地化、渠道和启动计划。',
        '请识别跨境数据、税务、贸易和用工风险并形成整改清单。',
      ],
    },
  },
  {
    id: 'bidding-management',
    version: 1,
    name: '招投标专家团',
    description: '从招标解读、资格审查、技术商务方案、报价、合规到投标交付全流程协作。',
    category: 'function',
    tags: ['招标解读', '标书制作', '投标管理'],
    legacyNames: [],
    lead: lead(
      'bidding_director',
      '投标总监',
      '统筹投标决策、分工、合规、质量和交付节点。',
      'function',
      ['project-manager'],
      ['投标', '标书', '总监'],
    ),
    roles: [
      role(
        'tender_analyst',
        '招标文件分析师',
        '解读资格、评分、技术、商务、格式和废标条件。',
        ['pdf', 'docx'],
        'function',
        [],
        ['招标', '文件', '分析'],
      ),
      role(
        'qualification_manager',
        '投标资格经理',
        '核对资质、业绩、人员、授权和证明材料完整性。',
        ['docx', 'xlsx'],
        'function',
        [],
        ['投标资格', '资质', '经理'],
      ),
      role(
        'technical_proposal_writer',
        '技术方案顾问',
        '编写需求响应、总体方案、实施、服务和验收内容。',
        ['bidding-proposal', 'docx'],
        'tech',
        [],
        ['技术标', '方案', '顾问'],
      ),
      role(
        'commercial_proposal_analyst',
        '商务报价分析师',
        '设计报价结构、成本、条款响应和价格风险。',
        ['xlsx', 'docx'],
        'finance',
        ['finance-analyst'],
        ['商务标', '报价', '分析'],
      ),
      role(
        'bid_compliance_reviewer',
        '投标合规审核师',
        '执行响应矩阵、交叉检查、格式审校和封标清单。',
        ['bidding-proposal', 'pdf'],
        'legal',
        ['risk-assessment'],
        ['投标合规', '审核', '标书'],
      ),
    ],
    prompts: {
      primary: '请组织一次投标工作，完成招标解读、资格、技术方案、商务报价、合规检查和交付计划。',
      examples: [
        '请解读这份招标文件并生成评分点、废标项和任务分工。',
        '请根据需求编写技术方案框架、响应矩阵和证据清单。',
        '请在提交前对资格、技术、商务和格式做一次完整审标。',
      ],
    },
  },
];
