import type { ExpertRoleDefinition, ExpertTeamCategory, ExpertTeamDefinition } from './expertTeams';

type RoleSpec = readonly [
  key: string,
  name: string,
  description: string,
  skillIds: string[],
  category: ExpertTeamCategory,
  keywords: string[],
];

interface IndustryTeamSpec {
  id: string;
  name: string;
  description: string;
  category: ExpertTeamCategory;
  tags: [string, string, string];
  lead: readonly [key: string, name: string, description: string, keywords: string[]];
  roles: RoleSpec[];
  primary: string;
  examples: [string, string, string];
}

const createRole = (spec: RoleSpec): ExpertRoleDefinition => {
  const [key, name, description, skillIds, category, keywords] = spec;
  return {
    key,
    name,
    description,
    systemPrompt: [
      `你是专家团中的${name}。`,
      `你的职责是：${description}`,
      '只处理与你职责直接相关的工作；信息不足时明确列出需要补充的材料。',
      '先给结论和关键依据，再给可执行步骤、风险与待确认项。',
      '完成后把结构化结果交还主理人，不越权代表整个专家团作最终决策。',
    ].join('\n'),
    skillIds,
    avatarHints: {
      templateIds: [],
      keywords,
      category,
    },
  };
};

const createIndustryTeam = (spec: IndustryTeamSpec): ExpertTeamDefinition => {
  const [leadKey, leadName, leadDescription, leadKeywords] = spec.lead;
  return {
    id: spec.id,
    version: 1,
    name: spec.name,
    description: spec.description,
    category: spec.category,
    tags: spec.tags,
    legacyNames: [],
    lead: createRole([leadKey, leadName, leadDescription, [], spec.category, leadKeywords]),
    roles: spec.roles.map(createRole),
    prompts: {
      primary: spec.primary,
      examples: spec.examples,
    },
  };
};

const INDUSTRY_TEAM_SPECS: IndustryTeamSpec[] = [
  {
    id: 'smart-manufacturing',
    name: '智能制造专家团',
    description: '围绕工厂数字化、自动化、工业数据、设备互联和智能决策推动制造升级。',
    category: 'tech',
    tags: ['智能工厂', '工业数字化', '自动化'],
    lead: [
      'smart_factory_director',
      '智能工厂总监',
      '统筹制造场景、技术路线、数据和落地价值。',
      ['智能制造', '工厂', '总监'],
    ],
    roles: [
      [
        'manufacturing_process_consultant',
        '制造流程顾问',
        '梳理生产流程、约束、关键控制点和数字化机会。',
        ['create-plan', 'xlsx'],
        'function',
        ['制造', '流程', '顾问'],
      ],
      [
        'industrial_automation_engineer',
        '工业自动化工程师',
        '规划设备、控制、机器人和自动化集成方案。',
        ['web-search', 'local-tools'],
        'tech',
        ['自动化', '设备', '工程师'],
      ],
      [
        'industrial_data_architect',
        '工业数据架构师',
        '设计设备数据、主数据、实时采集和分析架构。',
        ['local-tools', 'xlsx'],
        'tech',
        ['工业数据', '架构', '技术'],
      ],
      [
        'mes_solution_manager',
        '制造系统方案经理',
        '规划 MES、ERP、WMS、质量和设备系统协同。',
        ['web-search', 'create-plan'],
        'tech',
        ['MES', '制造系统', '经理'],
      ],
      [
        'smart_factory_value_analyst',
        '智能制造价值分析师',
        '评估效率、质量、成本、交付和投资回报。',
        ['xlsx'],
        'finance',
        ['制造', 'ROI', '分析'],
      ],
    ],
    primary: '请为我们的工厂制定智能制造升级路线图，覆盖流程、自动化、系统、数据和投资回报。',
    examples: [
      '请盘点工厂数字化场景并按价值和实施难度排序。',
      '请设计 MES、设备数据和质量系统的协同方案。',
      '请评估一条产线自动化改造的收益、风险和实施计划。',
    ],
  },
  {
    id: 'retail-chain',
    name: '连锁零售专家团',
    description: '协同选品、门店、会员、促销、供应和数据，提升连锁零售经营效率。',
    category: 'ecommerce',
    tags: ['连锁门店', '会员经营', '零售增长'],
    lead: [
      'retail_director',
      '零售经营总监',
      '统筹商品、门店、会员和供应链经营目标。',
      ['零售', '门店', '总监'],
    ],
    roles: [
      [
        'assortment_planner',
        '商品组合规划师',
        '优化品类、价格带、单品结构和门店差异化组合。',
        ['xlsx', 'web-search'],
        'ecommerce',
        ['商品', '零售', '规划'],
      ],
      [
        'store_operations_manager',
        '门店运营经理',
        '建立门店标准、排班、陈列、服务和巡店机制。',
        ['create-plan', 'xlsx'],
        'function',
        ['门店', '运营', '经理'],
      ],
      [
        'membership_operator',
        '会员运营经理',
        '设计会员分层、权益、触达、复购和流失挽回。',
        ['xlsx', 'content-planner'],
        'marketing',
        ['会员', '私域', '运营'],
      ],
      [
        'retail_promotion_manager',
        '零售促销经理',
        '规划档期、促销机制、资源和门店执行。',
        ['create-plan', 'xlsx'],
        'marketing',
        ['促销', '活动', '经理'],
      ],
      [
        'retail_data_analyst',
        '零售数据分析师',
        '分析客流、转化、客单、连带、库存和坪效。',
        ['xlsx'],
        'finance',
        ['零售数据', '经营', '分析'],
      ],
    ],
    primary: '请对我们的连锁零售业务制定商品、门店、会员、促销和数据运营方案。',
    examples: [
      '请分析门店坪效差异并制定分店改善计划。',
      '请为会员复购设计分层、权益和触达机制。',
      '请制定季度商品组合、促销日历和库存联动方案。',
    ],
  },
  {
    id: 'food-beverage',
    name: '食品饮料专家团',
    description: '覆盖产品创新、配方与质量、渠道、品牌、供应链和法规风险。',
    category: 'ecommerce',
    tags: ['食品创新', '渠道增长', '质量合规'],
    lead: [
      'food_business_director',
      '食品饮料业务总监',
      '统筹产品、质量、渠道、品牌和供应链决策。',
      ['食品', '消费品', '总监'],
    ],
    roles: [
      [
        'food_product_manager',
        '食品产品经理',
        '研究消费需求、产品概念、规格、价格和上市节奏。',
        ['web-search', 'create-plan'],
        'ecommerce',
        ['食品', '产品', '经理'],
      ],
      [
        'food_quality_specialist',
        '食品质量专家',
        '规划原料、生产、检测、保质期和追溯控制。',
        ['docx', 'xlsx'],
        'function',
        ['食品质量', '检测', '专家'],
      ],
      [
        'food_compliance_advisor',
        '食品法规顾问',
        '审查标签、宣称、广告、许可和食品安全要求。',
        ['web-search', 'pdf'],
        'legal',
        ['食品法规', '合规', '顾问'],
      ],
      [
        'channel_growth_manager',
        '食品渠道增长经理',
        '规划经销、商超、电商、餐饮和终端动销。',
        ['web-search', 'xlsx'],
        'marketing',
        ['渠道', '食品', '增长'],
      ],
      [
        'consumer_brand_planner',
        '消费品牌策划师',
        '设计品牌定位、包装表达、内容和上市传播。',
        ['content-planner', 'canvas-design'],
        'marketing',
        ['品牌', '包装', '策划'],
      ],
    ],
    primary: '请为一款食品饮料新品制定从产品、质量、合规到渠道和品牌上市的完整方案。',
    examples: [
      '请评估这个新品概念的消费者需求、竞品和价格带。',
      '请审查产品标签、宣传卖点和食品安全风险。',
      '请设计新品上市的渠道、内容和终端动销计划。',
    ],
  },
  {
    id: 'hospitality-management',
    name: '酒店经营专家团',
    description: '围绕收益、渠道、房务、餐饮、宾客体验和服务质量提升酒店经营。',
    category: 'function',
    tags: ['酒店运营', '收益管理', '宾客体验'],
    lead: [
      'hotel_general_manager',
      '酒店经营总经理',
      '统筹收入、成本、服务、品牌和运营协同。',
      ['酒店', '经营', '总经理'],
    ],
    roles: [
      [
        'revenue_manager',
        '酒店收益经理',
        '优化房价、库存、预测、渠道和收益策略。',
        ['xlsx', 'web-search'],
        'finance',
        ['酒店收益', '定价', '经理'],
      ],
      [
        'rooms_operations_manager',
        '房务运营经理',
        '管理前厅、客房、排班、清洁和服务标准。',
        ['create-plan', 'xlsx'],
        'function',
        ['酒店', '房务', '运营'],
      ],
      [
        'guest_experience_manager',
        '宾客体验经理',
        '设计宾客旅程、服务触点、投诉和口碑提升。',
        ['docx', 'content-planner'],
        'marketing',
        ['宾客', '服务', '经理'],
      ],
      [
        'hotel_channel_manager',
        '酒店渠道经理',
        '管理直销、OTA、会员、企业客户和渠道成本。',
        ['web-search', 'xlsx'],
        'marketing',
        ['OTA', '酒店渠道', '经理'],
      ],
      [
        'hotel_quality_analyst',
        '酒店质量分析师',
        '分析评分、投诉、服务偏差和改进效果。',
        ['xlsx', 'docx'],
        'function',
        ['酒店质量', '数据', '分析'],
      ],
    ],
    primary: '请对我们的酒店经营做一次诊断，覆盖收益、渠道、房务、宾客体验和服务质量。',
    examples: [
      '请制定淡季房价、渠道和会员促销策略。',
      '请优化从预订到离店的宾客体验和投诉处理流程。',
      '请建立酒店服务质量指标、巡检和复盘机制。',
    ],
  },
  {
    id: 'restaurant-chain',
    name: '连锁餐饮专家团',
    description: '协同菜单、门店、供应链、食品安全、外卖和会员增长。',
    category: 'ecommerce',
    tags: ['连锁餐饮', '门店效率', '食品安全'],
    lead: [
      'restaurant_operations_director',
      '餐饮运营总监',
      '统筹产品、门店、供应、质量和增长结果。',
      ['餐饮', '连锁', '总监'],
    ],
    roles: [
      [
        'menu_product_manager',
        '菜单产品经理',
        '规划品类、单品、价格、毛利、上新和淘汰。',
        ['xlsx', 'web-search'],
        'ecommerce',
        ['菜单', '产品', '经理'],
      ],
      [
        'restaurant_store_manager',
        '餐饮门店运营经理',
        '优化排班、出品、动线、服务和门店标准。',
        ['create-plan', 'xlsx'],
        'function',
        ['餐饮门店', '运营', '经理'],
      ],
      [
        'food_safety_manager',
        '食品安全经理',
        '建立采购、储存、加工、留样和检查机制。',
        ['docx', 'xlsx'],
        'function',
        ['食品安全', '餐饮', '经理'],
      ],
      [
        'delivery_operations_manager',
        '外卖运营经理',
        '优化平台菜单、活动、履约、评价和利润。',
        ['xlsx', 'content-planner'],
        'ecommerce',
        ['外卖', '运营', '经理'],
      ],
      [
        'restaurant_membership_analyst',
        '餐饮会员分析师',
        '分析到店、复购、券、活动和会员价值。',
        ['xlsx'],
        'marketing',
        ['餐饮会员', '复购', '分析'],
      ],
    ],
    primary: '请为我们的连锁餐饮业务制定菜单、门店、食品安全、外卖和会员增长方案。',
    examples: [
      '请分析门店利润下降并定位菜单、人工和外卖问题。',
      '请为新店开业制定运营、食品安全和营销计划。',
      '请设计会员复购、优惠券和外卖联动机制。',
    ],
  },
  {
    id: 'real-estate-development',
    name: '房地产开发专家团',
    description: '覆盖市场研判、投资测算、产品定位、开发计划、营销和风险管理。',
    category: 'finance',
    tags: ['地产投资', '项目开发', '营销去化'],
    lead: [
      'real_estate_director',
      '地产项目总监',
      '统筹投资、定位、开发、销售和项目风险。',
      ['地产', '项目', '总监'],
    ],
    roles: [
      [
        'real_estate_market_analyst',
        '地产市场分析师',
        '研究区域、供需、竞品、客群、价格和去化趋势。',
        ['web-search', 'xlsx'],
        'finance',
        ['地产市场', '区域', '分析'],
      ],
      [
        'investment_analyst',
        '地产投资分析师',
        '测算土地、开发成本、售价、现金流和投资回报。',
        ['xlsx'],
        'finance',
        ['地产投资', '测算', '分析'],
      ],
      [
        'product_positioning_manager',
        '地产产品定位经理',
        '定义客群、业态、户型、配套、价格和价值主张。',
        ['web-search', 'pptx'],
        'marketing',
        ['地产产品', '定位', '经理'],
      ],
      [
        'development_plan_manager',
        '开发计划经理',
        '制定报批、设计、招采、施工、交付和资金节点。',
        ['create-plan', 'xlsx'],
        'function',
        ['地产开发', '计划', '经理'],
      ],
      [
        'real_estate_marketing_manager',
        '地产营销经理',
        '规划案名、渠道、推广、销售节奏和去化策略。',
        ['content-planner', 'xlsx'],
        'marketing',
        ['地产营销', '销售', '经理'],
      ],
    ],
    primary: '请对一个房地产项目完成市场、投资、产品、开发计划和营销去化的联合研判。',
    examples: [
      '请评估一个地块的市场机会、投资回报和主要风险。',
      '请为住宅项目制定客群、产品、价格和去化策略。',
      '请建立从拿地到交付的开发总计划和关键决策点。',
    ],
  },
  {
    id: 'construction-engineering',
    name: '建筑工程专家团',
    description: '协同设计、造价、计划、施工、质量安全和竣工交付。',
    category: 'function',
    tags: ['工程管理', '成本进度', '质量安全'],
    lead: [
      'engineering_director',
      '工程项目总监',
      '统筹范围、成本、进度、质量、安全和交付。',
      ['工程', '项目', '总监'],
    ],
    roles: [
      [
        'design_coordination_manager',
        '设计协调经理',
        '管理设计任务、专业接口、审图、变更和技术交底。',
        ['docx', 'create-plan'],
        'design',
        ['工程设计', '协调', '经理'],
      ],
      [
        'cost_engineer',
        '工程造价师',
        '分析工程量、目标成本、清单、签证和结算。',
        ['xlsx', 'pdf'],
        'finance',
        ['造价', '成本', '工程'],
      ],
      [
        'construction_planner',
        '施工计划工程师',
        '编制施工组织、进度、资源和关键路径计划。',
        ['create-plan', 'xlsx'],
        'function',
        ['施工', '计划', '工程师'],
      ],
      [
        'quality_safety_manager',
        '工程质量安全经理',
        '建立检查、验收、隐患、整改和应急机制。',
        ['docx', 'xlsx'],
        'function',
        ['质量安全', '工程', '经理'],
      ],
      [
        'contract_change_manager',
        '工程合同变更经理',
        '管理合同边界、变更、索赔、证据和结算风险。',
        ['docx', 'pdf'],
        'legal',
        ['工程合同', '变更', '经理'],
      ],
    ],
    primary: '请为这个建设项目制定设计、造价、施工、质量安全和合同变更管理方案。',
    examples: [
      '请编制工程项目总进度、关键路径和资源计划。',
      '请审查工程变更、签证和索赔风险。',
      '请建立施工质量安全检查、验收和整改闭环。',
    ],
  },
  {
    id: 'automotive-industry',
    name: '汽车产业专家团',
    description: '围绕车型规划、研发、供应链、质量、渠道和售后支持汽车业务决策。',
    category: 'tech',
    tags: ['汽车研发', '供应链质量', '渠道售后'],
    lead: [
      'automotive_business_director',
      '汽车业务总监',
      '统筹产品、研发、供应、质量和市场目标。',
      ['汽车', '产业', '总监'],
    ],
    roles: [
      [
        'vehicle_product_planner',
        '车型产品规划师',
        '研究细分市场、用户、配置、价格和车型生命周期。',
        ['web-search', 'xlsx'],
        'marketing',
        ['汽车产品', '车型', '规划'],
      ],
      [
        'automotive_engineering_manager',
        '汽车研发项目经理',
        '管理研发范围、节点、试制、验证和工程变更。',
        ['create-plan', 'xlsx'],
        'tech',
        ['汽车研发', '工程', '经理'],
      ],
      [
        'automotive_supply_chain_analyst',
        '汽车供应链分析师',
        '评估零部件供应、产能、成本和中断风险。',
        ['xlsx', 'web-search'],
        'logistics',
        ['汽车供应链', '零部件', '分析'],
      ],
      [
        'automotive_quality_engineer',
        '汽车质量工程师',
        '规划供应商、过程、整车和售后质量闭环。',
        ['docx', 'xlsx'],
        'function',
        ['汽车质量', '工程师', '测试'],
      ],
      [
        'dealer_service_manager',
        '渠道与售后经理',
        '设计经销、交付、服务、备件和客户满意度机制。',
        ['create-plan', 'xlsx'],
        'marketing',
        ['汽车售后', '渠道', '经理'],
      ],
    ],
    primary: '请对一个汽车产品项目制定市场、研发、供应链、质量和渠道售后协同方案。',
    examples: [
      '请评估一款新车型的细分市场、配置和价格策略。',
      '请建立车型研发、试制、验证和上市节点计划。',
      '请诊断供应链和售后质量问题并给出改善动作。',
    ],
  },
  {
    id: 'new-energy',
    name: '新能源产业专家团',
    description: '覆盖政策市场、技术路线、项目开发、供应链、经济性和安全风险。',
    category: 'tech',
    tags: ['新能源', '项目投资', '技术路线'],
    lead: [
      'new_energy_director',
      '新能源业务总监',
      '统筹市场、技术、项目、经济性和风险决策。',
      ['新能源', '项目', '总监'],
    ],
    roles: [
      [
        'energy_policy_analyst',
        '能源政策分析师',
        '研究政策、市场机制、补贴、消纳和区域机会。',
        ['web-search'],
        'function',
        ['能源政策', '市场', '分析'],
      ],
      [
        'energy_technology_specialist',
        '新能源技术专家',
        '评估光伏、储能、风电、充电或氢能技术路线。',
        ['web-search', 'local-tools'],
        'tech',
        ['新能源技术', '工程', '专家'],
      ],
      [
        'energy_project_development_manager',
        '能源项目开发经理',
        '规划选址、资源、许可、并网、建设和运营。',
        ['create-plan', 'docx'],
        'function',
        ['能源项目', '开发', '经理'],
      ],
      [
        'energy_financial_analyst',
        '能源经济性分析师',
        '测算投资、发电或服务收入、成本、现金流和敏感性。',
        ['xlsx'],
        'finance',
        ['新能源投资', '财务', '分析'],
      ],
      [
        'energy_safety_risk_manager',
        '能源安全风险经理',
        '识别设备、施工、消防、并网和运行风险。',
        ['docx', 'web-search'],
        'function',
        ['能源安全', '风险', '经理'],
      ],
    ],
    primary: '请对一个新能源项目完成政策、技术、开发、经济性和安全风险的联合评估。',
    examples: [
      '请评估一个储能项目的市场机制、技术方案和投资回报。',
      '请为分布式光伏项目制定开发、并网和建设计划。',
      '请建立新能源项目安全风险清单和应急机制。',
    ],
  },
  {
    id: 'semiconductor-industry',
    name: '半导体产业专家团',
    description: '覆盖产业链、产品定义、研发制造、供应保障、质量和市场策略。',
    category: 'tech',
    tags: ['半导体', '芯片研发', '产业链'],
    lead: [
      'semiconductor_director',
      '半导体业务总监',
      '统筹产品、技术、制造、供应和商业化。',
      ['半导体', '芯片', '总监'],
    ],
    roles: [
      [
        'semiconductor_market_analyst',
        '半导体市场分析师',
        '研究细分市场、应用、竞争、周期和客户需求。',
        ['web-search', 'xlsx'],
        'marketing',
        ['半导体市场', '芯片', '分析'],
      ],
      [
        'chip_product_manager',
        '芯片产品经理',
        '定义应用、规格、性能、成本、路线图和量产目标。',
        ['docx', 'web-search'],
        'tech',
        ['芯片产品', '规格', '经理'],
      ],
      [
        'chip_development_manager',
        '芯片研发项目经理',
        '管理设计、验证、流片、封测和量产导入节点。',
        ['create-plan', 'xlsx'],
        'tech',
        ['芯片研发', '项目', '经理'],
      ],
      [
        'semiconductor_supply_manager',
        '半导体供应保障经理',
        '规划晶圆、封测、材料、设备和产能风险。',
        ['xlsx', 'web-search'],
        'logistics',
        ['半导体供应链', '产能', '经理'],
      ],
      [
        'semiconductor_quality_engineer',
        '半导体质量工程师',
        '管理可靠性、失效分析、良率和客户质量。',
        ['xlsx', 'docx'],
        'function',
        ['半导体质量', '工程师', '良率'],
      ],
    ],
    primary: '请为一个半导体产品制定市场、产品、研发、供应链和质量量产方案。',
    examples: [
      '请分析一个芯片细分市场的客户需求、竞争和进入机会。',
      '请建立从产品定义到流片量产的项目计划。',
      '请诊断良率、供应保障和客户质量风险。',
    ],
  },
  {
    id: 'healthcare-operations',
    name: '医疗健康专家团',
    description: '围绕医疗服务、患者体验、运营效率、质量安全、数据和合规开展协同。',
    category: 'healthcare',
    tags: ['医疗运营', '患者服务', '质量安全'],
    lead: [
      'healthcare_director',
      '医疗运营总监',
      '统筹服务质量、效率、患者体验和合规边界。',
      ['医疗', '健康', '总监'],
    ],
    roles: [
      [
        'healthcare_service_designer',
        '医疗服务流程顾问',
        '梳理预约、就诊、检查、治疗、随访和转诊流程。',
        ['create-plan', 'docx'],
        'healthcare',
        ['医疗服务', '流程', '顾问'],
      ],
      [
        'patient_experience_manager',
        '患者体验经理',
        '设计患者旅程、沟通、服务、投诉和随访机制。',
        ['docx', 'xlsx'],
        'healthcare',
        ['患者', '服务', '经理'],
      ],
      [
        'medical_quality_manager',
        '医疗质量经理',
        '规划质量指标、不良事件、检查和持续改进。',
        ['xlsx', 'docx'],
        'healthcare',
        ['医疗质量', '安全', '经理'],
      ],
      [
        'healthcare_data_analyst',
        '医疗运营分析师',
        '分析服务量、效率、资源、患者结构和运营指标。',
        ['xlsx'],
        'healthcare',
        ['医疗数据', '运营', '分析'],
      ],
      [
        'healthcare_compliance_advisor',
        '医疗合规顾问',
        '识别资质、宣传、隐私、收费和执业边界风险。',
        ['web-search', 'pdf'],
        'legal',
        ['医疗合规', '法务', '顾问'],
      ],
    ],
    primary: '请对我们的医疗服务机构开展运营诊断，覆盖流程、患者体验、质量安全、数据和合规。',
    examples: [
      '请优化预约、就诊、检查和随访的患者服务流程。',
      '请建立医疗质量安全指标和不良事件改进机制。',
      '请审查医疗宣传、患者隐私和服务合规风险。',
    ],
  },
  {
    id: 'pharmaceutical-industry',
    name: '医药产业专家团',
    description: '覆盖研发管线、临床与注册、生产质量、市场准入和商业化。',
    category: 'healthcare',
    tags: ['医药研发', '注册准入', '商业化'],
    lead: [
      'pharma_director',
      '医药业务总监',
      '统筹管线价值、合规里程碑、供应和商业化。',
      ['医药', '研发', '总监'],
    ],
    roles: [
      [
        'pipeline_strategy_analyst',
        '医药管线策略师',
        '评估疾病领域、未满足需求、竞争和管线优先级。',
        ['web-search', 'xlsx'],
        'healthcare',
        ['医药管线', '研发', '策略'],
      ],
      [
        'clinical_development_manager',
        '临床开发经理',
        '规划临床问题、试验阶段、证据和关键节点。',
        ['web-search', 'create-plan'],
        'healthcare',
        ['临床', '医药', '经理'],
      ],
      [
        'regulatory_affairs_advisor',
        '药品注册顾问',
        '梳理注册路径、资料、沟通、审评和变更要求。',
        ['web-search', 'pdf'],
        'legal',
        ['药品注册', '法规', '顾问'],
      ],
      [
        'pharma_quality_manager',
        '药品质量经理',
        '管理生产质量、偏差、变更、验证和供应商风险。',
        ['docx', 'xlsx'],
        'healthcare',
        ['药品质量', '生产', '经理'],
      ],
      [
        'market_access_manager',
        '医药市场准入经理',
        '研究支付、定价、准入、证据和商业化路径。',
        ['web-search', 'xlsx'],
        'marketing',
        ['医药准入', '市场', '经理'],
      ],
    ],
    primary: '请对一个医药产品制定从管线、临床、注册、质量到市场准入的完整策略。',
    examples: [
      '请评估一个疾病领域的未满足需求和管线机会。',
      '请建立临床开发、注册申报和关键证据计划。',
      '请制定产品定价、市场准入和商业化准备方案。',
    ],
  },
  {
    id: 'education-training',
    name: '教育培训专家团',
    description: '协同课程研发、教学设计、招生增长、学习运营、教研质量和合规。',
    category: 'education',
    tags: ['课程研发', '教学运营', '招生增长'],
    lead: [
      'education_business_director',
      '教育业务总监',
      '统筹产品、教学、增长、服务和合规质量。',
      ['教育', '培训', '总监'],
    ],
    roles: [
      [
        'curriculum_product_manager',
        '课程产品经理',
        '定义学习人群、目标、课程体系、产品形态和价格。',
        ['web-search', 'docx'],
        'education',
        ['课程', '产品', '经理'],
      ],
      [
        'instructional_designer',
        '教学设计师',
        '设计学习目标、内容、活动、作业和评价。',
        ['docx', 'pptx'],
        'education',
        ['教学', '课程', '设计'],
      ],
      [
        'teaching_operations_manager',
        '教学运营经理',
        '管理排课、师资、班级、学习进度和服务触点。',
        ['create-plan', 'xlsx'],
        'education',
        ['教学运营', '班级', '经理'],
      ],
      [
        'enrollment_growth_manager',
        '招生增长经理',
        '设计目标人群、渠道、内容、咨询和转化路径。',
        ['content-planner', 'xlsx'],
        'marketing',
        ['招生', '增长', '经理'],
      ],
      [
        'education_compliance_advisor',
        '教育合规顾问',
        '审查资质、收费、合同、宣传、未成年人和数据风险。',
        ['web-search', 'pdf'],
        'legal',
        ['教育合规', '法务', '顾问'],
      ],
    ],
    primary: '请为一个教育培训项目制定课程、教学、运营、招生和合规一体化方案。',
    examples: [
      '请为目标学员设计课程体系、教学活动和评价机制。',
      '请诊断招生转化和完课率问题并提出改进方案。',
      '请审查课程宣传、收费合同和未成年人合规风险。',
    ],
  },
  {
    id: 'banking-operations',
    name: '银行业务专家团',
    description: '围绕客户、产品、信贷、风险、运营和监管支持银行经营决策。',
    category: 'finance',
    tags: ['银行经营', '信贷风险', '监管合规'],
    lead: [
      'banking_director',
      '银行业务总监',
      '统筹客户、产品、风险、运营和监管要求。',
      ['银行', '金融', '总监'],
    ],
    roles: [
      [
        'bank_customer_strategist',
        '银行客户策略师',
        '分析客群、需求、价值分层和客户经营路径。',
        ['xlsx', 'web-search'],
        'finance',
        ['银行客户', '金融', '策略'],
      ],
      [
        'bank_product_manager',
        '银行产品经理',
        '规划存款、贷款、支付、财富或企业金融产品。',
        ['docx', 'xlsx'],
        'finance',
        ['银行产品', '金融', '经理'],
      ],
      [
        'credit_risk_analyst',
        '信贷风险分析师',
        '评估客户信用、还款能力、担保、行业和组合风险。',
        ['xlsx', 'web-search'],
        'finance',
        ['信贷', '风险', '分析'],
      ],
      [
        'bank_operations_manager',
        '银行运营经理',
        '优化开户、审批、放款、支付、对账和服务流程。',
        ['create-plan', 'xlsx'],
        'function',
        ['银行运营', '流程', '经理'],
      ],
      [
        'bank_compliance_advisor',
        '银行合规顾问',
        '识别反洗钱、消费者保护、数据和监管报告风险。',
        ['web-search', 'pdf'],
        'legal',
        ['银行合规', '监管', '顾问'],
      ],
    ],
    primary: '请对一项银行业务制定客户、产品、信贷风险、运营和合规协同方案。',
    examples: [
      '请为小微企业贷款产品设计客户、流程和风险政策。',
      '请诊断贷款审批效率和资产质量问题。',
      '请建立银行客户经营指标和监管合规检查清单。',
    ],
  },
  {
    id: 'insurance-operations',
    name: '保险经营专家团',
    description: '覆盖产品、精算、渠道、核保理赔、客户服务和合规风控。',
    category: 'finance',
    tags: ['保险产品', '渠道经营', '核保理赔'],
    lead: [
      'insurance_director',
      '保险经营总监',
      '统筹产品价值、风险、渠道、服务和合规。',
      ['保险', '金融', '总监'],
    ],
    roles: [
      [
        'insurance_product_manager',
        '保险产品经理',
        '定义客群、保障责任、条款、定价目标和产品组合。',
        ['docx', 'web-search'],
        'finance',
        ['保险产品', '保障', '经理'],
      ],
      [
        'actuarial_analyst',
        '精算分析师',
        '分析发生率、费率、准备金、利润和情景敏感性。',
        ['xlsx'],
        'finance',
        ['精算', '保险', '分析'],
      ],
      [
        'insurance_channel_manager',
        '保险渠道经理',
        '规划代理、银保、经纪、互联网和渠道激励。',
        ['xlsx', 'create-plan'],
        'marketing',
        ['保险渠道', '销售', '经理'],
      ],
      [
        'underwriting_claims_advisor',
        '核保理赔顾问',
        '设计核保规则、理赔流程、反欺诈和服务标准。',
        ['docx', 'xlsx'],
        'finance',
        ['核保', '理赔', '顾问'],
      ],
      [
        'insurance_compliance_manager',
        '保险合规经理',
        '审查销售行为、条款、信息披露、数据和监管要求。',
        ['web-search', 'pdf'],
        'legal',
        ['保险合规', '监管', '经理'],
      ],
    ],
    primary: '请为一项保险业务制定产品、精算、渠道、核保理赔和合规经营方案。',
    examples: [
      '请评估一个保险产品的客群、责任、定价和盈利假设。',
      '请诊断渠道销售质量、退保和投诉问题。',
      '请优化核保理赔流程并建立反欺诈控制。',
    ],
  },
  {
    id: 'logistics-delivery',
    name: '物流运输专家团',
    description: '围绕网络、运输、仓储、调度、成本、服务和安全提升物流履约。',
    category: 'logistics',
    tags: ['物流网络', '运输调度', '履约成本'],
    lead: [
      'logistics_operations_director',
      '物流运营总监',
      '统筹网络、资源、时效、成本、安全和客户服务。',
      ['物流', '运输', '总监'],
    ],
    roles: [
      [
        'logistics_network_planner',
        '物流网络规划师',
        '设计仓网、线路、节点、覆盖和资源配置。',
        ['xlsx', 'web-search'],
        'logistics',
        ['物流网络', '规划', '运输'],
      ],
      [
        'transport_dispatch_manager',
        '运输调度经理',
        '优化车辆、司机、班次、路线、装载和异常调度。',
        ['xlsx', 'create-plan'],
        'logistics',
        ['运输', '调度', '经理'],
      ],
      [
        'warehouse_operations_manager',
        '仓储运营经理',
        '管理入库、存储、拣选、出库、盘点和人员效率。',
        ['create-plan', 'xlsx'],
        'logistics',
        ['仓储', '运营', '经理'],
      ],
      [
        'logistics_cost_analyst',
        '物流成本分析师',
        '拆解线路、车辆、仓储、人工和单位履约成本。',
        ['xlsx'],
        'finance',
        ['物流成本', '运输', '分析'],
      ],
      [
        'delivery_quality_manager',
        '履约质量经理',
        '分析时效、破损、丢失、投诉、安全和承运商质量。',
        ['xlsx', 'docx'],
        'function',
        ['履约', '物流质量', '经理'],
      ],
    ],
    primary: '请对我们的物流业务制定网络、运输、仓储、成本和履约质量优化方案。',
    examples: [
      '请优化仓网、线路和车辆配置以降低单位履约成本。',
      '请诊断运输延误和仓储效率问题。',
      '请建立物流时效、质量、安全和承运商管理机制。',
    ],
  },
  {
    id: 'modern-agriculture',
    name: '现代农业专家团',
    description: '覆盖品种与种植、农资、生产计划、质量追溯、供应链和品牌销售。',
    category: 'logistics',
    tags: ['农业生产', '质量追溯', '产销协同'],
    lead: [
      'agriculture_director',
      '农业产业总监',
      '统筹生产、质量、供应链、市场和经营风险。',
      ['农业', '产业', '总监'],
    ],
    roles: [
      [
        'agriculture_market_analyst',
        '农产品市场分析师',
        '研究供需、价格、渠道、区域和品类机会。',
        ['web-search', 'xlsx'],
        'marketing',
        ['农产品', '市场', '分析'],
      ],
      [
        'crop_production_planner',
        '农业生产规划师',
        '制定品种、面积、农时、投入、产量和采收计划。',
        ['create-plan', 'xlsx'],
        'logistics',
        ['农业生产', '种植', '规划'],
      ],
      [
        'agriculture_quality_manager',
        '农产品质量经理',
        '建立投入品、生产、检测、采后和追溯控制。',
        ['docx', 'xlsx'],
        'function',
        ['农产品质量', '追溯', '经理'],
      ],
      [
        'agriculture_supply_chain_manager',
        '农产品供应链经理',
        '规划采收、分选、仓储、冷链、运输和损耗控制。',
        ['xlsx', 'create-plan'],
        'logistics',
        ['农业供应链', '冷链', '经理'],
      ],
      [
        'agriculture_brand_operator',
        '农产品品牌运营',
        '设计品牌、包装、内容、渠道和产地故事。',
        ['content-planner', 'canvas-design'],
        'marketing',
        ['农产品品牌', '运营', '包装'],
      ],
    ],
    primary: '请为一个农业项目制定生产、质量追溯、供应链和品牌销售一体化方案。',
    examples: [
      '请制定一个种植季的品种、投入、农时和产量计划。',
      '请建立农产品质量追溯和冷链损耗控制机制。',
      '请为区域农产品设计品牌、包装和渠道方案。',
    ],
  },
  {
    id: 'cultural-tourism',
    name: '文旅运营专家团',
    description: '围绕目的地、产品、内容、渠道、游客体验和活动运营打造文旅增长。',
    category: 'marketing',
    tags: ['文旅策划', '游客体验', '目的地营销'],
    lead: [
      'tourism_director',
      '文旅运营总监',
      '统筹资源、产品、营销、服务和经营结果。',
      ['文旅', '旅游', '总监'],
    ],
    roles: [
      [
        'destination_strategy_planner',
        '目的地策略规划师',
        '研究资源、客群、竞品、季节和目的地定位。',
        ['web-search', 'pptx'],
        'marketing',
        ['目的地', '旅游', '规划'],
      ],
      [
        'tourism_product_manager',
        '文旅产品经理',
        '设计线路、场景、票务、住宿、餐饮和组合产品。',
        ['create-plan', 'xlsx'],
        'marketing',
        ['旅游产品', '线路', '经理'],
      ],
      [
        'visitor_experience_designer',
        '游客体验设计师',
        '规划行前、到达、游览、消费、服务和离场体验。',
        ['docx', 'canvas-design'],
        'design',
        ['游客体验', '服务', '设计'],
      ],
      [
        'destination_content_operator',
        '目的地内容运营',
        '策划短视频、图文、话题、达人和节庆传播。',
        ['content-planner', 'article-writer'],
        'content',
        ['文旅内容', '目的地', '运营'],
      ],
      [
        'tourism_operations_analyst',
        '文旅经营分析师',
        '分析客流、转化、客单、停留、渠道和满意度。',
        ['xlsx'],
        'finance',
        ['文旅数据', '经营', '分析'],
      ],
    ],
    primary: '请为一个文旅目的地制定定位、产品、游客体验、内容传播和经营分析方案。',
    examples: [
      '请为一个淡季目的地设计主题产品和获客活动。',
      '请优化游客从行前到离场的全旅程体验。',
      '请制定文旅内容矩阵、渠道计划和经营指标。',
    ],
  },
  {
    id: 'media-entertainment',
    name: '传媒娱乐专家团',
    description: '协同内容开发、IP、制作、发行、商业化和舆情风险。',
    category: 'content',
    tags: ['内容制作', 'IP 运营', '发行商业化'],
    lead: [
      'media_business_director',
      '传媒业务总监',
      '统筹内容价值、制作资源、发行和商业结果。',
      ['传媒', '内容', '总监'],
    ],
    roles: [
      [
        'content_development_producer',
        '内容开发制片人',
        '研究受众、选题、故事、形式和项目立项。',
        ['content-planner', 'web-search'],
        'content',
        ['内容开发', '制片', '策划'],
      ],
      [
        'ip_strategy_manager',
        'IP 运营经理',
        '规划 IP 定位、角色、内容矩阵、授权和长期经营。',
        ['pptx', 'content-planner'],
        'content',
        ['IP', '内容', '运营'],
      ],
      [
        'production_manager',
        '制作统筹经理',
        '管理脚本、预算、人员、拍摄、后期和交付节点。',
        ['create-plan', 'xlsx'],
        'content',
        ['制作', '项目', '经理'],
      ],
      [
        'distribution_growth_manager',
        '发行增长经理',
        '制定平台、档期、宣发、用户增长和数据复盘。',
        ['daily-trending', 'xlsx'],
        'marketing',
        ['发行', '增长', '经理'],
      ],
      [
        'media_commercialization_advisor',
        '内容商业化顾问',
        '设计广告、会员、付费、授权和品牌合作模式。',
        ['xlsx', 'docx'],
        'finance',
        ['商业化', '传媒', '顾问'],
      ],
    ],
    primary: '请为一个传媒内容项目制定开发、制作、IP、发行和商业化完整方案。',
    examples: [
      '请评估一个内容选题的受众、平台和商业化潜力。',
      '请制定从脚本到上线的制作计划和预算框架。',
      '请为一个 IP 设计内容矩阵、发行和授权路径。',
    ],
  },
  {
    id: 'saas-business',
    name: 'SaaS 经营专家团',
    description: '围绕产品市场匹配、定价、获客、销售、实施、客户成功和续费增长。',
    category: 'tech',
    tags: ['SaaS 增长', '订阅经营', '客户成功'],
    lead: [
      'saas_business_director',
      'SaaS 业务总监',
      '统筹产品、增长、收入、交付和续费目标。',
      ['SaaS', '软件', '总监'],
    ],
    roles: [
      [
        'saas_product_strategist',
        'SaaS 产品策略师',
        '定义目标客户、核心场景、产品价值和路线图。',
        ['web-search', 'create-plan'],
        'tech',
        ['SaaS 产品', '软件', '策略'],
      ],
      [
        'saas_pricing_analyst',
        'SaaS 定价分析师',
        '设计版本、计费指标、价格、折扣和单位经济模型。',
        ['xlsx', 'web-search'],
        'finance',
        ['SaaS 定价', '订阅', '分析'],
      ],
      [
        'saas_growth_manager',
        'SaaS 增长经理',
        '规划内容、试用、线索、产品增长和转化实验。',
        ['content-planner', 'xlsx'],
        'marketing',
        ['SaaS 增长', '获客', '经理'],
      ],
      [
        'implementation_success_manager',
        '实施成功经理',
        '管理上线、配置、培训、价值实现和风险升级。',
        ['create-plan', 'docx'],
        'function',
        ['SaaS 实施', '客户成功', '经理'],
      ],
      [
        'subscription_analyst',
        '订阅经营分析师',
        '分析 ARR、留存、扩张、流失、回收期和客户健康。',
        ['xlsx'],
        'finance',
        ['SaaS 数据', '订阅', '分析'],
      ],
    ],
    primary: '请为我们的 SaaS 业务制定产品、定价、获客、实施和续费增长方案。',
    examples: [
      '请诊断 SaaS 获客成本高和转化率低的问题。',
      '请设计版本、计费指标、价格和折扣体系。',
      '请建立客户上线、健康度、续费和扩张机制。',
    ],
  },
  {
    id: 'public-sector-services',
    name: '政企公共服务专家团',
    description: '围绕公共服务需求、政策、项目建设、数据治理、运营评估和合规交付。',
    category: 'function',
    tags: ['政企项目', '公共服务', '合规交付'],
    lead: [
      'public_service_director',
      '公共服务项目总监',
      '统筹政策目标、公众需求、项目建设和合规成效。',
      ['政企', '公共服务', '总监'],
    ],
    roles: [
      [
        'public_policy_analyst',
        '公共政策分析师',
        '解读政策目标、职责、对象、约束和实施要求。',
        ['web-search', 'pdf'],
        'function',
        ['政策', '公共服务', '分析'],
      ],
      [
        'public_service_designer',
        '公共服务设计师',
        '研究服务对象、事项、触点、无障碍和办理体验。',
        ['docx', 'canvas-design'],
        'design',
        ['公共服务', '体验', '设计'],
      ],
      [
        'government_project_manager',
        '政企项目经理',
        '管理范围、采购、计划、验收、档案和协同。',
        ['create-plan', 'xlsx'],
        'function',
        ['政企项目', '交付', '经理'],
      ],
      [
        'public_data_governance_advisor',
        '公共数据治理顾问',
        '规划数据目录、共享、授权、质量、安全和开放边界。',
        ['docx', 'xlsx'],
        'tech',
        ['公共数据', '治理', '顾问'],
      ],
      [
        'public_value_evaluator',
        '公共价值评估师',
        '评估覆盖、效率、公平、满意度和财政绩效。',
        ['xlsx', 'pptx'],
        'finance',
        ['公共价值', '绩效', '评估'],
      ],
    ],
    primary: '请为一个政企公共服务项目制定政策解读、服务设计、建设、数据治理和成效评估方案。',
    examples: [
      '请把一项公共政策转化为项目目标、服务对象和实施任务。',
      '请优化一个政务服务事项的办理流程和用户体验。',
      '请建立政企项目验收、数据治理和公共价值评估指标。',
    ],
  },
  {
    id: 'home-appliance-industry',
    name: '电器行业专家团',
    description: '围绕电器产品规划、研发认证、供应质量、渠道销售和售后服务支持电器企业经营决策。',
    category: 'tech',
    tags: ['电器研发', '渠道零售', '售后服务'],
    lead: [
      'appliance_business_director',
      '电器业务总监',
      '统筹产品、研发、制造、渠道和售后经营目标。',
      ['电器', '家电', '总监'],
    ],
    roles: [
      [
        'appliance_product_planner',
        '电器产品规划师',
        '研究品类趋势、用户需求、功能配置、价格带和产品生命周期。',
        ['web-search', 'xlsx'],
        'marketing',
        ['电器产品', '家电', '规划'],
      ],
      [
        'appliance_rd_engineering_manager',
        '电器研发工程经理',
        '管理电气安全、能效、可靠性测试、认证和工程变更。',
        ['create-plan', 'docx'],
        'tech',
        ['电器研发', '认证', '工程'],
      ],
      [
        'appliance_supply_quality_analyst',
        '电器供应与质量分析师',
        '评估核心部件供应、产能、成本、来料和产线质量闭环。',
        ['xlsx', 'web-search'],
        'logistics',
        ['电器供应链', '质量', '分析'],
      ],
      [
        'appliance_channel_manager',
        '电器渠道运营经理',
        '规划线上线下渠道、经销商、门店促销、电商大促和价格管控。',
        ['create-plan', 'xlsx'],
        'ecommerce',
        ['电器渠道', '电商', '经理'],
      ],
      [
        'appliance_aftersales_manager',
        '电器售后服务经理',
        '设计安装、维修、备件、延保、投诉处理和满意度机制。',
        ['docx', 'xlsx'],
        'function',
        ['电器售后', '服务', '经理'],
      ],
      [
        'appliance_market_analyst',
        '电器市场数据分析师',
        '分析销量、市占、价格、竞品、能效政策和以旧换新补贴影响。',
        ['xlsx'],
        'finance',
        ['电器市场', '数据', '分析'],
      ],
    ],
    primary: '请为一个电器产品项目制定市场、研发认证、供应质量、渠道销售和售后服务协同方案。',
    examples: [
      '请评估一款新家电的细分市场、功能配置和价格策略。',
      '请建立电器研发、能效与安全认证和上市节点计划。',
      '请诊断渠道动销和售后投诉问题并给出改善动作。',
    ],
  },
  {
    id: 'real-estate-services',
    name: '房地产行业专家团',
    description: '围绕房产交易经纪、租赁运营、物业服务、资产管理和政策合规支持房地产企业经营。',
    category: 'finance',
    tags: ['交易经纪', '物业运营', '资产管理'],
    lead: [
      'real_estate_business_director',
      '房地产业务总监',
      '统筹交易、租赁、物业、资管和合规经营目标。',
      ['房地产', '行业', '总监'],
    ],
    roles: [
      [
        'property_transaction_manager',
        '房产交易经纪经理',
        '设计房源获取、客户匹配、带看转化、签约和佣金管理机制。',
        ['create-plan', 'xlsx'],
        'marketing',
        ['房产交易', '经纪', '经理'],
      ],
      [
        'leasing_operations_manager',
        '租赁运营经理',
        '规划住宅长租和商办租赁的定价、招租、续租和空置管理。',
        ['xlsx', 'web-search'],
        'function',
        ['租赁', '运营', '经理'],
      ],
      [
        'property_management_advisor',
        '物业服务顾问',
        '建立物业服务标准、收费、报修、社区运营和满意度机制。',
        ['docx', 'create-plan'],
        'function',
        ['物业', '服务', '顾问'],
      ],
      [
        'real_estate_asset_manager',
        '房地产资产管理师',
        '评估持有物业的租金收益、估值、改造和处置策略。',
        ['xlsx'],
        'finance',
        ['资产管理', '估值', '分析'],
      ],
      [
        'housing_policy_compliance_advisor',
        '房产政策合规顾问',
        '解读限购限贷、税费、预售资金监管和交易合规要求。',
        ['web-search', 'pdf'],
        'legal',
        ['房产政策', '合规', '顾问'],
      ],
      [
        'real_estate_customer_experience_manager',
        '房产客户体验经理',
        '设计客户全周期触点、投诉处理、口碑和转介绍机制。',
        ['content-planner', 'xlsx'],
        'marketing',
        ['客户体验', '房产', '经理'],
      ],
    ],
    primary: '请为一家房地产服务企业制定交易经纪、租赁运营、物业服务、资产管理和政策合规协同方案。',
    examples: [
      '请设计二手房交易从房源获取到签约成交的转化提升方案。',
      '请评估一批持有物业的租金收益、估值和改造处置策略。',
      '请梳理当前限购限贷和税费政策对交易流程的合规要求。',
    ],
  },
];

export const INDUSTRY_EXPERT_TEAM_DEFINITIONS: ExpertTeamDefinition[] =
  INDUSTRY_TEAM_SPECS.map(createIndustryTeam);
