import { languageToolsTranslations } from './languageToolsCopy';

export const desktopCompanionTranslations = {
  zh: {
    ...languageToolsTranslations.zh,
    desktopCompanionTitle: '悬浮球',
    desktopCompanionGroupDisplay: '显示',
    desktopCompanionGroupFeatures: '功能',
    desktopCompanionGroupQuickPanel: '快捷面板',
    desktopCompanionEnable: '在桌面显示悬浮球',
    desktopCompanionEnableDescription: '一只常驻桌面的小龙虾「钳钳」。你选中文字、拖动文档、切换应用时，它就在手边。',
    desktopCompanionDisable: '关闭悬浮球',
    desktopCompanionOpenPanel: '打开快捷面板',
    desktopCompanionShortcut: '全局快捷键',
    desktopCompanionShortcutHint: '点此录入组合键',
    desktopCompanionShortcutDescription: '未设置快捷键。配置后，即使关闭悬浮球，也能随时打开快捷面板。',
    desktopCompanionShortcutConflict: '快捷键无效或已被占用，原快捷键已保留。请换一个组合。',
    desktopCompanionShortcutUnavailable: '快捷键暂不可用，请重新设置。',
    desktopCompanionSettingsSaved: '设置立即生效。关闭后，下次启动仍保持关闭。',
    desktopCompanionSkin: '形象',
    desktopCompanionSkinDescription: '默认是钳钳，也可以换成海洋伙伴。',
    desktopCompanionSkinLobster: '钳钳',
    desktopCompanionSkinRuanruanxia: '软软虾',
    desktopCompanionSkinXingxingxing: '醒醒星',
    desktopCompanionSkinShaee: '鲨饿饿',
    desktopCompanionSkinZhangduoduo: '章多多',
    desktopCompanionSkinJingyiming: '鲸一鸣',
    desktopCompanionSkinLiuliuyu: '溜溜鱼',
    desktopCompanionSkinDanpapa: '胆怕怕',
    desktopCompanionSkinQingqingpiao: '轻轻飘',
    desktopCompanionSelection: '划词工具条',
    desktopCompanionSelectionDescription: '在任意应用中选中文字，即可一键翻译、朗读、解释、总结、润色。只有点了按钮才会发送选中的内容。',
    desktopCompanionSelectionNeedsPermission: '需要在系统设置中为 LobsterAI 打开「辅助功能」权限，才能读取选中的文字。',
    desktopCompanionSelectionUnsupported: '当前系统暂不支持划词。',
    desktopCompanionGrantPermission: '去授权',
    desktopCompanionDragAssist: '拖文件投放区',
    desktopCompanionDragAssistDescription: '拖动文档时，钳钳旁会展开投放区，拖到格子上就直接开始。',
    desktopCompanionDragAssistLimited: '当前系统只支持把文件直接拖到钳钳身上。',
    desktopCompanionHints: '情境提示',
    desktopCompanionHintsDescription: '根据你正在用的应用，偶尔提一句 Lobster 能帮上什么。每天最多 3 次，只在本机判断，不读取窗口内容。',
    desktopCompanionExcludedApps: '不显示划词的应用',
    desktopCompanionExcludedAppsEmpty: '可以在划词条的「⋯」里把当前应用加进来。',
    desktopCompanionRemoveExcludedApp: '移除',
    desktopCompanionOrbIdle: '有事找我',
    desktopCompanionOrbRunning: '正在处理…',
    desktopCompanionOrbDone: '做好了，点我看看',
    desktopCompanionOrbWaiting: '需要你确认一下',
    desktopCompanionOrbError: '遇到了问题',
    desktopCompanionOrbSnoozed: '打盹中，右键可叫醒',
    desktopCompanionSnoozeHour: '隐藏 1 小时',
    desktopCompanionTaskView: '查看',
    desktopCompanionTaskHandle: '去处理',
    desktopCompanionNeedsModel: '还没有可用的模型，请先在 LobsterAI 里登录或添加模型。',
    desktopCompanionSnoozeToday: '今天不再打扰',
    desktopCompanionWake: '叫醒钳钳',
    desktopCompanionChangeSkin: '换个形象',
    desktopCompanionSettings: '设置…',
    desktopCompanionHintWelcome0: '嗨，我是你的桌面龙虾。选中文字、把文件拖给我，或者点我交代任务，都可以。',
    desktopCompanionHintDocument0: '写材料、改文档这类活，可以找我当秘书。',
    desktopCompanionHintDocument1: '下次写文档，先把要点丢给我，我来起个草。',
    desktopCompanionHintSpreadsheet0: '表格里的数，可以直接丢给我分析。',
    desktopCompanionHintSpreadsheet1: '重复整理表格的活，可以交给我来做。',
    desktopCompanionHintPresentation0: '做 PPT 之前，先让我帮你理一理思路。',
    desktopCompanionHintMail0: '邮件这件事，可以交给我每天例行看一遍。',
    desktopCompanionHintMail1: '回邮件卡壳的时候，可以让我先起个草。',
    desktopCompanionHintBrowser0: '网页上的重复操作，可以让我替你点。',
    desktopCompanionHintBrowser1: '查资料、比价格这类事，可以让我开着浏览器替你跑。',
    desktopCompanionHintChat0: '群里的长消息和文件，可以转给我整理。',
    desktopCompanionHintFiles0: '乱糟糟的文件夹，可以交给我整理。',
    desktopCompanionHintPdf0: '长文档别硬啃，拖给我先看要点。',
    desktopCompanionHintCalendar0: '每天的日程，我可以一早提醒你。',
    desktopCompanionHintNotes0: '零散的笔记，我可以帮你整理成文。',
    desktopCompanionHintActionTry: '试试看',
    desktopCompanionHintActionMail: '每天早上帮我看',
    desktopCompanionHintActionCalendar: '每天早上提醒我',
    desktopCompanionHintDismiss: '知道了',
    desktopCompanionHintMute: '不再提示这类',
    desktopCompanionPromptDocument: '帮我起草一份文档，主题是：',
    desktopCompanionPromptSpreadsheet: '帮我分析这份表格，重点关注：',
    desktopCompanionPromptPresentation: '我要做一份关于「」的 PPT，先帮我列一个大纲。',
    desktopCompanionPromptMail: '每天早上 9 点帮我查看邮箱，整理出需要我处理的邮件，并给出建议回复。',
    desktopCompanionPromptBrowser: '帮我打开浏览器，',
    desktopCompanionPromptChat: '帮我整理这段聊天记录的要点和待办：',
    desktopCompanionPromptFiles: '帮我整理这个文件夹，按类型和用途分类：',
    desktopCompanionPromptPdf: '帮我读一下这份 PDF，列出要点：',
    desktopCompanionPromptCalendar: '每天早上 8:30 提醒我今天的日程安排。',
    desktopCompanionPromptNotes: '帮我把这些笔记整理成一篇结构清晰的文档：',
    desktopCompanionDropTitle: '松手交给我',
    desktopCompanionDropTitleIdle: '把文档拖到这里，让我帮你看看',
    desktopCompanionDropFilesCount: '{count} 个文件',
    desktopCompanionDropStarting: '收到，开始处理…',
    desktopCompanionDropFailed: '没能开始任务，可以到主窗口重试。',
    desktopCompanionDropDigest: '解读要点',
    desktopCompanionDropDigestDetail: '几分钟读懂',
    desktopCompanionDropDigestPrompt: '请阅读我提供的文件，帮我快速读懂：先用一段话说明它讲了什么，再列出关键要点、重要数据，以及需要我注意或跟进的事项。',
    desktopCompanionDropTranslate: '翻译全文',
    desktopCompanionDropTranslateDetail: '中英互译',
    desktopCompanionDropTranslatePrompt: '请把我提供的文件翻译成另一种语言（中文译成英文，其他语言译成中文），尽量保留原有结构和格式，把译文保存为新文件放在原文件旁边，并告诉我保存位置。',
    desktopCompanionDropAnalyze: '分析数据',
    desktopCompanionDropAnalyzeDetail: '趋势与异常',
    desktopCompanionDropAnalyzePrompt: '请分析我提供的表格：说明数据结构，计算关键指标，找出趋势、异常和值得关注的地方，用结论加要点的方式呈现。',
    desktopCompanionDropChart: '做成图表',
    desktopCompanionDropChartDetail: '一眼看懂',
    desktopCompanionDropChartPrompt: '请根据我提供的表格，挑选最能说明问题的 1–3 个角度做成图表并保存为图片，再用几句话解读。',
    desktopCompanionDropOutline: '提炼要点',
    desktopCompanionDropOutlineDetail: '逐页梳理',
    desktopCompanionDropOutlinePrompt: '请提炼我提供的演示文稿：按页梳理核心观点，最后给出一页纸的整体总结。',
    desktopCompanionDropScript: '写讲稿',
    desktopCompanionDropScriptDetail: '口语化讲稿',
    desktopCompanionDropScriptPrompt: '请根据我提供的演示文稿，为每一页写一段口语化的讲稿，整体时长控制在 5–8 分钟。',
    desktopCompanionDropOcr: '识别文字',
    desktopCompanionDropOcrDetail: '保留版式',
    desktopCompanionDropOcrPrompt: '请识别图片中的文字，按原有版式整理输出；如果是表格，请整理成 Markdown 表格。',
    desktopCompanionDropDescribe: '解释图片',
    desktopCompanionDropDescribeDetail: '看懂图里的信息',
    desktopCompanionDropDescribePrompt: '请解释这张图片：它展示了什么、关键信息是什么、有哪些值得注意的地方。',
    desktopCompanionDropOrganize: '整理归纳',
    desktopCompanionDropOrganizeDetail: '分类与汇总',
    desktopCompanionDropOrganizePrompt: '请帮我整理这些文件：说明每个文件是什么，给出分类建议，并汇总其中的关键信息。',
    desktopCompanionDropAsk: '问点别的',
    desktopCompanionDropAskDetail: '带着文件提问',
    desktopCompanionDropAskPrompt: '',
    desktopCompanionActionTranslate: '翻译',
    desktopCompanionActionExplain: '解释',
    desktopCompanionActionSummarize: '总结',
    desktopCompanionActionPolish: '润色',
    desktopCompanionActionAsk: '问问',
    desktopCompanionSelectionMore: '更多',
    desktopCompanionSelectionCopy: '复制',
    desktopCompanionSelectionCopied: '已复制',
    desktopCompanionSelectionExclude: '在这个应用里不显示',
    desktopCompanionSelectionPause: '暂停划词 1 小时',
    desktopCompanionSelectionSettings: '划词设置',
    desktopCompanionTranslateToZh: '译成中文',
    desktopCompanionTranslateToEn: '译成英文',
    desktopCompanionAnswerFollowUp: '继续追问…',
    desktopCompanionAnswerAskPlaceholder: '想问关于这段内容的什么？',
    desktopCompanionAnswerToTask: '转为任务',
    desktopCompanionAnswerRetry: '重试',
    desktopCompanionAnswerStop: '停止',
    desktopCompanionAnswerPin: '固定',
    desktopCompanionAnswerUnpin: '取消固定',
    desktopCompanionAnswerClose: '关闭',
    desktopCompanionAnswerThinking: '正在思考…',
    desktopCompanionAnswerNoModel: '还没有可用的模型，请先在设置里配置。',
    desktopCompanionAnswerFailed: '没有拿到回答：{error}',
    desktopCompanionTaskFromSelection: '下面是我在其他应用中选中的内容，以及你刚才的回答。请在此基础上继续帮我处理。\n\n<selected_text>\n{text}\n</selected_text>\n\n你的回答：\n{answer}\n\n我的要求：',
    desktopCompanionDrop: '松手放入材料',
    desktopCompanionFolder: '工作区',
    desktopCompanionSend: '交给我',
    desktopCompanionOpenApp: '打开 LobsterAI',
    desktopCompanionHide: '收起',
    desktopCompanionRunning: '进行中',
    desktopCompanionDone: '已完成',
    desktopCompanionIdle: '已暂停',
    desktopCompanionFailed: '需要处理',
    desktopCompanionWaiting: '需要你确认',
    desktopCompanionStop: '停止',
    desktopCompanionRequestFailed: '操作未成功，请重试，或到主窗口继续。',
    desktopCompanionImageFailed: '图片未能准备好，请移除后重新添加，或到主窗口提交。',
    desktopCompanionLoading: '正在读取任务…',
  },
  en: {
    ...languageToolsTranslations.en,
    desktopCompanionTitle: 'Floating Orb',
    desktopCompanionGroupDisplay: 'Display',
    desktopCompanionGroupFeatures: 'Features',
    desktopCompanionGroupQuickPanel: 'Quick panel',
    desktopCompanionEnable: 'Show the floating orb',
    desktopCompanionEnableDescription: 'A little lobster named Clawdie lives on your desktop. It is at hand when you select text, drag a document, or switch apps.',
    desktopCompanionDisable: 'Turn off floating orb',
    desktopCompanionOpenPanel: 'Open quick panel',
    desktopCompanionShortcut: 'Global shortcut',
    desktopCompanionShortcutHint: 'Click and press a shortcut',
    desktopCompanionShortcutDescription: 'No shortcut is set. A shortcut can open the quick panel even when the floating orb is off.',
    desktopCompanionShortcutConflict: 'This shortcut is invalid or already in use. Your previous shortcut was kept.',
    desktopCompanionShortcutUnavailable: 'The shortcut is unavailable. Please set it again.',
    desktopCompanionSettingsSaved: 'Changes apply immediately. Turning it off keeps it off at the next launch.',
    desktopCompanionSkin: 'Character',
    desktopCompanionSkinDescription: 'Clawdie by default, or pick a sea friend.',
    desktopCompanionSkinLobster: 'Clawdie',
    desktopCompanionSkinRuanruanxia: 'Squishy Shrimp',
    desktopCompanionSkinXingxingxing: 'Wakey Star',
    desktopCompanionSkinShaee: 'Hungry Shark',
    desktopCompanionSkinZhangduoduo: 'Octo Lots',
    desktopCompanionSkinJingyiming: 'Whale Whoa',
    desktopCompanionSkinLiuliuyu: 'Zippy Fish',
    desktopCompanionSkinDanpapa: 'Timid Puff',
    desktopCompanionSkinQingqingpiao: 'Drifty Jelly',
    desktopCompanionSelection: 'Selection toolbar',
    desktopCompanionSelectionDescription: 'Translate, read aloud, explain, summarize, or polish selected text in any app. Text is sent only after you click an action.',
    desktopCompanionSelectionNeedsPermission: 'Turn on Accessibility for LobsterAI in System Settings so it can read selected text.',
    desktopCompanionSelectionUnsupported: 'The selection toolbar is not supported on this system.',
    desktopCompanionGrantPermission: 'Grant access',
    desktopCompanionDragAssist: 'Drop zone for files',
    desktopCompanionDragAssistDescription: 'While you drag a document, a drop zone opens next to Clawdie. Drop on a tile to start.',
    desktopCompanionDragAssistLimited: 'On this system, drop files onto Clawdie itself.',
    desktopCompanionHints: 'Contextual tips',
    desktopCompanionHintsDescription: 'Occasionally suggests how Lobster can help with the app you are using. At most 3 a day, decided on this device without reading window contents.',
    desktopCompanionExcludedApps: 'Apps without the selection toolbar',
    desktopCompanionExcludedAppsEmpty: 'Add the current app from the toolbar\'s "⋯" menu.',
    desktopCompanionRemoveExcludedApp: 'Remove',
    desktopCompanionOrbIdle: 'Need a hand?',
    desktopCompanionOrbRunning: 'Working on it…',
    desktopCompanionOrbDone: 'Done — click to view',
    desktopCompanionOrbWaiting: 'Needs your confirmation',
    desktopCompanionOrbError: 'Something went wrong',
    desktopCompanionOrbSnoozed: 'Snoozing — right-click to wake',
    desktopCompanionSnoozeHour: 'Hide for 1 hour',
    desktopCompanionTaskView: 'View',
    desktopCompanionTaskHandle: 'Respond',
    desktopCompanionNeedsModel: 'No model is available yet. Sign in or add a model in LobsterAI first.',
    desktopCompanionSnoozeToday: 'Quiet for today',
    desktopCompanionWake: 'Wake Clawdie',
    desktopCompanionChangeSkin: 'Change character',
    desktopCompanionSettings: 'Settings…',
    desktopCompanionHintWelcome0: 'Hi, I\'m your desktop Lobster. Select text, drag a file onto me, or click me to hand over a task.',
    desktopCompanionHintDocument0: 'Writing and editing documents? I can be your secretary.',
    desktopCompanionHintDocument1: 'Next time, toss me the key points and I will draft the document.',
    desktopCompanionHintSpreadsheet0: 'Numbers in a spreadsheet? Hand them to me to analyze.',
    desktopCompanionHintSpreadsheet1: 'I can take over repetitive spreadsheet cleanup.',
    desktopCompanionHintPresentation0: 'Before building slides, let me help you shape the story.',
    desktopCompanionHintMail0: 'I can go through your email for you every day.',
    desktopCompanionHintMail1: 'Stuck on a reply? Let me write the first draft.',
    desktopCompanionHintBrowser0: 'Repetitive clicking on websites? I can do it for you.',
    desktopCompanionHintBrowser1: 'Research and price checks can run in the browser while you work.',
    desktopCompanionHintChat0: 'Long group chats and shared files? Forward them to me to sort out.',
    desktopCompanionHintFiles0: 'A messy folder? I can organize it for you.',
    desktopCompanionHintPdf0: 'Long document? Drop it on me for the key points first.',
    desktopCompanionHintCalendar0: 'I can brief you on your schedule every morning.',
    desktopCompanionHintNotes0: 'Scattered notes? I can turn them into a clean document.',
    desktopCompanionHintActionTry: 'Try it',
    desktopCompanionHintActionMail: 'Check every morning',
    desktopCompanionHintActionCalendar: 'Remind me every morning',
    desktopCompanionHintDismiss: 'Got it',
    desktopCompanionHintMute: 'Don\'t show these',
    desktopCompanionPromptDocument: 'Help me draft a document about: ',
    desktopCompanionPromptSpreadsheet: 'Analyze this spreadsheet, focusing on: ',
    desktopCompanionPromptPresentation: 'I need slides about "". Start with an outline.',
    desktopCompanionPromptMail: 'Every morning at 9, check my inbox, list the emails I need to handle, and suggest replies.',
    desktopCompanionPromptBrowser: 'Open the browser and ',
    desktopCompanionPromptChat: 'Summarize the key points and to-dos from this chat: ',
    desktopCompanionPromptFiles: 'Organize this folder by type and purpose: ',
    desktopCompanionPromptPdf: 'Read this PDF and list the key points: ',
    desktopCompanionPromptCalendar: 'Every morning at 8:30, remind me of today\'s schedule.',
    desktopCompanionPromptNotes: 'Turn these notes into a well-structured document: ',
    desktopCompanionDropTitle: 'Drop it on me',
    desktopCompanionDropTitleIdle: 'Drag your document here',
    desktopCompanionDropFilesCount: '{count} files',
    desktopCompanionDropStarting: 'Got it, starting…',
    desktopCompanionDropFailed: 'Could not start the task. Try again from the main window.',
    desktopCompanionDropDigest: 'Key points',
    desktopCompanionDropDigestDetail: 'Get the gist',
    desktopCompanionDropDigestPrompt: 'Read the files I provide and help me understand them quickly: one paragraph on what they cover, then the key points, important numbers, and anything I need to follow up on.',
    desktopCompanionDropTranslate: 'Translate',
    desktopCompanionDropTranslateDetail: 'Chinese ↔ English',
    desktopCompanionDropTranslatePrompt: 'Translate the files I provide (Chinese into English, other languages into Chinese), keeping structure and formatting. Save the translation as a new file next to the original and tell me where it is.',
    desktopCompanionDropAnalyze: 'Analyze',
    desktopCompanionDropAnalyzeDetail: 'Trends & outliers',
    desktopCompanionDropAnalyzePrompt: 'Analyze the spreadsheet I provide: describe its structure, compute the key metrics, and point out trends, anomalies, and anything notable as a takeaway plus bullet points.',
    desktopCompanionDropChart: 'Chart it',
    desktopCompanionDropChartDetail: 'See it at a glance',
    desktopCompanionDropChartPrompt: 'Using the spreadsheet I provide, chart the 1–3 most telling views, save them as images, and explain them in a few sentences.',
    desktopCompanionDropOutline: 'Outline',
    desktopCompanionDropOutlineDetail: 'Slide by slide',
    desktopCompanionDropOutlinePrompt: 'Distill the presentation I provide: the core point of each slide, then a one-page overall summary.',
    desktopCompanionDropScript: 'Speaker notes',
    desktopCompanionDropScriptDetail: 'Ready to present',
    desktopCompanionDropScriptPrompt: 'Write conversational speaker notes for each slide of the presentation I provide, about 5–8 minutes in total.',
    desktopCompanionDropOcr: 'Extract text',
    desktopCompanionDropOcrDetail: 'Keep the layout',
    desktopCompanionDropOcrPrompt: 'Extract the text in the image and keep its layout; turn any tables into Markdown tables.',
    desktopCompanionDropDescribe: 'Explain image',
    desktopCompanionDropDescribeDetail: 'What it shows',
    desktopCompanionDropDescribePrompt: 'Explain this image: what it shows, the key information, and anything worth noticing.',
    desktopCompanionDropOrganize: 'Organize',
    desktopCompanionDropOrganizeDetail: 'Sort & summarize',
    desktopCompanionDropOrganizePrompt: 'Help me organize these files: say what each file is, suggest categories, and summarize the key information.',
    desktopCompanionDropAsk: 'Ask something',
    desktopCompanionDropAskDetail: 'Ask with the file',
    desktopCompanionDropAskPrompt: '',
    desktopCompanionActionTranslate: 'Translate',
    desktopCompanionActionExplain: 'Explain',
    desktopCompanionActionSummarize: 'Summarize',
    desktopCompanionActionPolish: 'Polish',
    desktopCompanionActionAsk: 'Ask',
    desktopCompanionSelectionMore: 'More',
    desktopCompanionSelectionCopy: 'Copy',
    desktopCompanionSelectionCopied: 'Copied',
    desktopCompanionSelectionExclude: 'Hide in this app',
    desktopCompanionSelectionPause: 'Pause for 1 hour',
    desktopCompanionSelectionSettings: 'Selection settings',
    desktopCompanionTranslateToZh: 'To Chinese',
    desktopCompanionTranslateToEn: 'To English',
    desktopCompanionAnswerFollowUp: 'Ask a follow-up…',
    desktopCompanionAnswerAskPlaceholder: 'What would you like to know about it?',
    desktopCompanionAnswerToTask: 'Make it a task',
    desktopCompanionAnswerRetry: 'Retry',
    desktopCompanionAnswerStop: 'Stop',
    desktopCompanionAnswerPin: 'Pin',
    desktopCompanionAnswerUnpin: 'Unpin',
    desktopCompanionAnswerClose: 'Close',
    desktopCompanionAnswerThinking: 'Thinking…',
    desktopCompanionAnswerNoModel: 'No model is available yet. Configure one in Settings first.',
    desktopCompanionAnswerFailed: 'Could not get an answer: {error}',
    desktopCompanionTaskFromSelection: 'Below is text I selected in another app and your answer. Please keep helping me from here.\n\n<selected_text>\n{text}\n</selected_text>\n\nYour answer:\n{answer}\n\nWhat I need: ',
    desktopCompanionDrop: 'Drop your materials here',
    desktopCompanionFolder: 'Workspace',
    desktopCompanionSend: 'Start',
    desktopCompanionOpenApp: 'Open LobsterAI',
    desktopCompanionHide: 'Hide',
    desktopCompanionRunning: 'Working',
    desktopCompanionDone: 'Done',
    desktopCompanionIdle: 'Paused',
    desktopCompanionFailed: 'Needs attention',
    desktopCompanionWaiting: 'Needs confirmation',
    desktopCompanionStop: 'Stop',
    desktopCompanionRequestFailed: 'The action failed. Try again or continue in the main window.',
    desktopCompanionImageFailed: 'Could not prepare the image. Remove it and add it again, or use the main window.',
    desktopCompanionLoading: 'Loading task…',
  },
};
