export const languageToolsTranslations = {
  zh: {
    desktopToolsTitle: '翻译与朗读', desktopToolsReadAloud: '朗读', desktopToolsPlayback: '朗读控制',
    desktopToolsInput: '原文', desktopToolsPlaceholder: '选中文字，或在这里粘贴内容…',
    desktopToolsTarget: '翻译目标语言', desktopToolsAuto: '自动中英互译', desktopToolsCharacters: ' 字',
    desktopToolsTranslation: '译文', desktopToolsReadTranslation: '朗读译文', desktopToolsTranslating: '正在翻译…',
    desktopToolsDetectLanguage: '自动检测', desktopToolsChinese: '简体中文', desktopToolsEnglish: '英语',
    desktopToolsRetranslate: '重新翻译', desktopToolsQuestion: '追问', desktopToolsReply: '回复',
    desktopToolsSegmentProgress: '第 {current} / {total} 段', desktopToolsSegmentLabel: '已播放段落',
    desktopToolsReady: '准备朗读', desktopToolsPreparing: '正在准备声音…', desktopToolsPlaying: '正在朗读',
    desktopToolsPaused: '已暂停', desktopToolsFinished: '朗读结束', desktopToolsAudioError: '播放失败，可尝试重新播放',
    desktopToolsPause: '暂停', desktopToolsResume: '继续 / 重新播放', desktopToolsStop: '停止', desktopToolsSpeed: '播放速度',
    desktopToolsBackground: '可收起，继续听', desktopToolsMinimize: '收起，保留朗读', desktopToolsClose: '关闭并停止',
    desktopToolsRemaining: '今日还可使用 {count} 次', desktopToolsRemainingCharacters: '可朗读 {count} 字',
    desktopToolsResetTime: '北京时间每日 00:00 恢复额度', desktopToolsQuotaHint: '登录即可使用，每日额度所有用户相同',
    desktopToolsLogin: '去登录', desktopToolsLoginRequired: '请先登录 LobsterAI，再使用翻译和朗读。',
    desktopToolsUnavailable: '翻译与朗读暂不可用，请稍后重试。', desktopToolsInvalidInput: '请输入有效的文本。',
    desktopToolsTooLong: '内容过长。翻译每次最多 5,000 字，朗读最多 100,000 字且受今日剩余额度限制。',
    desktopToolsDailyLimit: '今日剩余额度不足，请缩短朗读内容，或在北京时间明日 00:00 后再试。',
    desktopToolsRateLimit: '操作有些频繁，请稍等一分钟再试。',
    desktopToolsDuplicate: '这次请求已被受理，请等待结果。如需重新生成，请再次点击。',
    desktopToolsUpstream: '服务暂未完成请求，请重试。已生成的部分仍可使用。',
  },
  en: {
    desktopToolsTitle: 'Translate & read aloud', desktopToolsReadAloud: 'Read aloud', desktopToolsPlayback: 'Read-aloud controls',
    desktopToolsInput: 'Original text', desktopToolsPlaceholder: 'Select text in an app, or paste it here…',
    desktopToolsTarget: 'Target language', desktopToolsAuto: 'Auto Chinese / English', desktopToolsCharacters: ' chars',
    desktopToolsTranslation: 'Translation', desktopToolsReadTranslation: 'Read translation aloud', desktopToolsTranslating: 'Translating…',
    desktopToolsDetectLanguage: 'Detect language', desktopToolsChinese: 'Chinese', desktopToolsEnglish: 'English',
    desktopToolsRetranslate: 'Translate again', desktopToolsQuestion: 'Question', desktopToolsReply: 'Answer',
    desktopToolsSegmentProgress: 'Part {current} / {total}', desktopToolsSegmentLabel: 'Completed parts',
    desktopToolsReady: 'Ready to read', desktopToolsPreparing: 'Preparing audio…', desktopToolsPlaying: 'Reading aloud',
    desktopToolsPaused: 'Paused', desktopToolsFinished: 'Finished', desktopToolsAudioError: 'Playback failed. Try playing again.',
    desktopToolsPause: 'Pause', desktopToolsResume: 'Resume / replay', desktopToolsStop: 'Stop', desktopToolsSpeed: 'Playback speed',
    desktopToolsBackground: 'Keep listening when hidden', desktopToolsMinimize: 'Hide and keep listening', desktopToolsClose: 'Close and stop',
    desktopToolsRemaining: '{count} uses left today', desktopToolsRemainingCharacters: '{count} characters left',
    desktopToolsResetTime: 'Resets daily at 00:00 Beijing time', desktopToolsQuotaHint: 'Sign in to use. The same daily limits apply to everyone.',
    desktopToolsLogin: 'Sign in', desktopToolsLoginRequired: 'Sign in to LobsterAI to translate and read aloud.',
    desktopToolsUnavailable: 'Language tools are unavailable. Please try again later.', desktopToolsInvalidInput: 'Enter valid text to continue.',
    desktopToolsTooLong: 'The text is too long. Translation allows 5,000 characters; read-aloud allows 100,000, subject to your remaining daily quota.',
    desktopToolsDailyLimit: 'Not enough quota left today. Shorten the text or try after 00:00 Beijing time tomorrow.',
    desktopToolsRateLimit: 'Too many requests. Please wait a minute.',
    desktopToolsDuplicate: 'This request was already accepted. Wait for the result, or click again to generate a new one.',
    desktopToolsUpstream: 'The service could not finish. Please try again. Any completed output is still available.',
  },
};
